// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: 3107
 *     }
 */
export interface DeleteSipTrunksRequest {
    /** The unique ID of the SIP trunk. */
    id: number;
}
