// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListSipTrunksRequest {
    /** Page number to retrieve. Default `1`. */
    page?: number;
    /** Number of records to return per page. Default `25`. */
    per_page?: number;
}
