// This file was auto-generated by Fern from our API Definition.

import type * as Wavix from "../../../../index.js";

/**
 * @example
 *     {
 *         id: 3107,
 *         body: {
 *             label: "My trunk",
 *             password: "4r=h;EaCB85QNtr2",
 *             callerid: "13132847320",
 *             ip_restrict: false,
 *             didinfo_enabled: true,
 *             call_restrict: true,
 *             cost_limit: true,
 *             channels_restrict: false,
 *             rewrite_enabled: true,
 *             transcription_enabled: true,
 *             transcription_threshold: 10
 *         }
 *     }
 */
export interface UpdateSipTrunksRequest {
    /** The unique ID of the SIP trunk. */
    id: number;
    body: Wavix.SipTrunkCreateRequest;
}
