// This file was auto-generated by Fern from our API Definition.

/**
 * Represents a 10DLC campaign registered under a Brand. A Campaign defines the messaging use case, opt-in and opt-out flows, and the phone numbers permitted to send its traffic.
 */
export interface GetCampaignsResponse {
    /** Indicates whether the Campaign is used for affiliate marketing. */
    affiliate_marketing: boolean;
    /** Indicates whether the Campaign messages contain age-gated content. */
    age_gated: boolean;
    /** Indicates whether the Campaign should be automatically renewed. */
    auto_renewal: boolean;
    /** Date and time the Campaign was last billed in ISO 8601 format. `null` if the Campaign has never been billed. */
    last_bill_date: string | null;
    /** Date and time the Campaign will be billed next in ISO 8601 format. `null` if the next billing date is not scheduled. */
    next_bill_date: string | null;
    /** Indicates whether the Campaign messages contain direct lending content. */
    direct_lending: boolean;
    /** Indicates whether the Campaign messages contain embedded links. */
    embedded_links: boolean;
    /** Indicates whether the Campaign messages contain embedded phone numbers. */
    embedded_phones: boolean;
    /** Sample of an embedded link used in Campaign messages. */
    embedded_link_sample: string | null;
    /** Unique identifier of the Brand that owns the Campaign. */
    brand_id: string;
    /** Unique identifier of the Campaign assigned by the registry. */
    campaign_id: string;
    /** Description of the Campaign and its messaging purpose. */
    description: string | null;
    /** Description of the workflow through which subscribers opt in to the Campaign. */
    optin_workflow: string | null;
    /** Feedback from the registry explaining the current `status`. */
    feedback: string | null;
    /** Indicates whether the campaign includes a help system (for example, keyword: HELP, INFO). */
    help: boolean;
    /** Comma-separated list of help keywords. Keywords are case-insensitive. */
    help_keywords: string;
    /** Help message sent upon receiving a help keyword. */
    help_message: string | null;
    /** Indicates whether the Campaign requires subscriber opt-in. */
    optin: boolean;
    /** Comma-separated list of opt-in keywords. Keywords are case-insensitive. */
    optin_keywords: string;
    /** Opt-in message sent upon receiving an opt-in keyword. */
    optin_message: string | null;
    /** Indicates whether the campaign includes an opt-out system (for example, keyword: STOP, QUIT). */
    optout: boolean;
    /** Comma-separated list of opt-out keywords. Keywords are case-insensitive. */
    optout_keywords: string;
    /** Opt-out message sent upon receiving an opt-out keyword. */
    optout_message: string | null;
    /** Display name of the Campaign. */
    name: string;
    /** Timestamp when the Campaign was created, in ISO 8601 format. */
    created_at: string;
    /** Sample message demonstrating the content sent through the Campaign. */
    sample1: string | null;
    /** Sample message demonstrating the content sent through the Campaign. */
    sample2: string | null;
    /** Sample message demonstrating the content sent through the Campaign. */
    sample3: string | null;
    /** Sample message demonstrating the content sent through the Campaign. */
    sample4: string | null;
    /** Sample message demonstrating the content sent through the Campaign. */
    sample5: string | null;
    /** Timestamp when the Campaign was last updated, in ISO 8601 format. */
    updated_at: string;
    /** Indicates whether the Campaign is a mock campaign used for testing. Mock campaigns cannot send production traffic. */
    mock: boolean;
    /** Registered use case for the Campaign, such as `2FA` or `MARKETING`. */
    usecase: string;
    /** Recurring monthly fee charged for the Campaign, as a decimal string. */
    monthly_fee: string;
    /** Privacy policy URL. */
    privacy_policy: string | null;
    /** Terms and conditions URL. */
    terms_conditions: string | null;
    /** Current registration status of the Campaign, such as `APPROVED` or `PENDING`. */
    status: string;
    /** Phone numbers assigned to the Campaign, in E.164 format. */
    phone_numbers: string[];
}
