// This file was auto-generated by Fern from our API Definition.

import type * as Wavix from "../../../../../index.js";

/**
 * Paginated list of 10DLC Campaigns.
 */
export interface ListCampaignsResponse {
    /** 10DLC Campaigns on the current page that match the filter criteria. */
    items: Wavix.TenDlcCampaign[];
    /** Pagination metadata for the result set. */
    pagination: ListCampaignsResponse.Pagination;
}

export namespace ListCampaignsResponse {
    /**
     * Pagination metadata for the result set.
     */
    export interface Pagination {
        /** Current page number. */
        current_page: number;
        /** Number of records per page. */
        per_page: number;
        /** Total number of records. */
        total: number;
        /** Total number of pages. */
        total_pages: number;
    }
}
