// This file was auto-generated by Fern from our API Definition.

import type * as Wavix from "../../../../index.js";

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface CallAnswerRequest {
    /** The `uuid` of the call. */
    id: string;
    /** Indicates whether the call should be recorded. */
    call_recording?: boolean;
    /** Indicates whether the call should be transcribed after it ends. */
    call_transcription?: boolean;
    /** WebSocket URL to stream the call. */
    stream_url?: string;
    /** Direction of audio streamed to `stream_url`. */
    stream_type?: Wavix.CallStreamType;
    /** Audio channel streamed to `stream_url`. */
    stream_channel?: Wavix.CallStreamChannel;
}
