// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         from: "+1234567890",
 *         to: "+1987654321",
 *         callback_url: "https://examples.com/callback"
 *     }
 */
export interface CallRequest {
    /** Caller ID. Must be an active or verified phone number on the account. */
    from: string;
    /** Destination number in E.164 format */
    to: string;
    /** The callback URL where Wavix sends the call status updates */
    callback_url: string;
    /** Specifies whether to record the call */
    recording?: boolean;
    /** Specifies whether the AMD is turned on for the call */
    voicemail_detection?: boolean;
    /** Call metadata */
    tag?: string;
    /** The ring timeout, in seconds, before the call is considered unanswered. */
    timeout?: number;
}
