// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface GetCallControlRequest {
    /** The `uuid` of the call. */
    id: string;
}
