// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id",
 *         tag: "marketing-campaign"
 *     }
 */
export interface UpdateCallRequest {
    /** The `uuid` of the call. */
    id: string;
    /** User-defined label attached to the Call for tracking or reporting. */
    tag: string;
}
