// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { InvoicesClient } from "../resources/invoices/client/Client.js";
import { TransactionsClient } from "../resources/transactions/client/Client.js";

export declare namespace BillingClient {
    export type Options = BaseClientOptions;
}

export class BillingClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<BillingClient.Options>;
    protected _transactions: TransactionsClient | undefined;
    protected _invoices: InvoicesClient | undefined;

    constructor(options: BillingClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get transactions(): TransactionsClient {
        return (this._transactions ??= new TransactionsClient(this._options));
    }

    public get invoices(): InvoicesClient {
        return (this._invoices ??= new InvoicesClient(this._options));
    }
}
