// This file was auto-generated by Fern from our API Definition.

export const DeleteCallWebhooksRequestEventType = {
    PostCall: "post-call",
    OnCall: "on-call",
} as const;
export type DeleteCallWebhooksRequestEventType =
    (typeof DeleteCallWebhooksRequestEventType)[keyof typeof DeleteCallWebhooksRequestEventType];
