// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         request_id: "e865ea07-25af-4fdd-876e-04b0d41d5ebd",
 *         callback_url: "https://you-site.com/webhook"
 *     }
 */
export interface SpeechAnalyticsRetranscribeRequest {
    /** The `request_id` of the transcription, returned when the file was uploaded. */
    request_id: string;
    /** Callback URL for transcription status updates. */
    callback_url: string;
    /** Indicates whether to enable insights generation. */
    insights?: boolean;
}
