// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         country_id: 1,
 *         city_id: 1
 *     }
 */
export interface ListNumbersRequest {
    /** The unique ID of the country. */
    country_id: number;
    /** The unique ID of the city. */
    city_id: number;
    /** When `true`, returns only text-enabled phone numbers. */
    text_enabled_only?: boolean;
    /** Page number to retrieve. Default `1`. */
    page?: number;
    /** Number of records to return per page. Default `25`. */
    per_page?: number;
}
