// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         service_id: "7204a030201211ee9fb47d093f2f127c",
 *         from: "2022-01-01",
 *         to: "2022-01-31"
 *     }
 */
export interface ListSessionsRequest {
    /** The unique ID of the 2FA service. */
    service_id: string;
    /** Start of the date range to query, in `YYYY-MM-DD` format. Inclusive. */
    from: string;
    /** End of the date range to query, in `YYYY-MM-DD` format. Inclusive. */
    to: string;
}
