// This file was auto-generated by Fern from our API Definition.

import type * as Wavix from "../../../../index.js";

/**
 * @example
 *     {
 *         id: 1,
 *         active: true,
 *         restricted: true,
 *         scopes_enabled: true,
 *         permitted_ips: ["192.168.1.1", "10.0.0.1"],
 *         label: "Production API Key"
 *     }
 */
export interface ApiKeyUpdateRequest {
    /** The unique ID of the API key. */
    id: number;
    /** Indicates whether the API key is active. */
    active?: boolean;
    /** Indicates whether the API key is restricted to the listed permitted IPs. */
    restricted?: boolean;
    /** Indicates whether per-resource scope permissions are enforced for the API key. */
    scopes_enabled?: boolean;
    /** IP addresses allowed to use the API key when restriction is enabled. */
    permitted_ips?: string[];
    /** Human-readable label for the API key. */
    label?: string;
    /** View, buy, release, and configure phone numbers, browse inventory, and manage the cart. */
    numbers?: Wavix.ApiKeyScopePermission;
    /** View, create, update, and delete SIP trunks and their settings. */
    trunks?: Wavix.ApiKeyScopePermission;
    /** Access call records and active calls, and control live call actions such as starting, answering, ending, audio playback, DTMF, streaming, and transcription requests. */
    calls?: Wavix.ApiKeyCallsScopePermission;
    /** Access message history and Sender IDs, send messages, manage opt-outs, and create or delete Sender IDs. */
    messages?: Wavix.ApiKeyScopePermission;
    /** List, download, and delete call recordings. */
    recordings?: Wavix.ApiKeyScopePermission;
    /** View campaign analytics and Sender ID or Brand status, schedule bulk voice or SMS campaigns, register Brands, and create short links. */
    campaigns?: Wavix.ApiKeyScopePermission;
    /** View 2FA service details and verification logs, trigger OTPs by voice or SMS, and validate verification codes. */
    two_fa?: Wavix.ApiKeyScopePermission;
    /** View number validation results and trigger single or bulk validation or HLR lookup requests. */
    validator?: Wavix.ApiKeyScopePermission;
    /** List, create, and delete webhooks. */
    webhooks?: Wavix.ApiKeyScopePermission;
    /** Manage widget tokens, including listing, viewing, creating, updating, and deleting them. */
    embeddable?: Wavix.ApiKeyScopePermission;
    /** Access statements, balance, payment methods, usage reports, and billing settings, including payment method updates. */
    billing?: Wavix.ApiKeyScopePermission;
    /** View and update account profile information and timezone. */
    account?: Wavix.ApiKeyScopePermission;
    /** Manage subaccounts: list and view them, create, update, and suspend them. */
    subaccounts?: Wavix.ApiKeyScopePermission;
}
