// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: 1
 *     }
 */
export interface DeleteApiKeysRequest {
    /** The unique ID of the API key. */
    id: number;
}
