// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         label: "production"
 *     }
 */
export interface ListApiKeysRequest {
    /** Filters API keys by `label`. Matches partial values. */
    label?: string;
}
