// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         session_id: "2953d4308f2e11ecb75fcdafd6d2d687"
 *     }
 */
export interface CancelVerificationRequest {
    /** The unique ID of the 2FA verification session. */
    session_id: string;
}
