// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         session_id: "2953d4308f2e11ecb75fcdafd6d2d687",
 *         code: "123456"
 *     }
 */
export interface TwoFactorVerificationCheckRequest {
    /** The unique ID of the 2FA verification session. */
    session_id: string;
    /** The code entered by an end user */
    code: string;
}
