// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         from: "2023-05-01",
 *         to: "2023-05-31",
 *         phone: "1872025555",
 *         utm_campaign: "summer",
 *         page: 1,
 *         per_page: 25
 *     }
 */
export interface ListMetricsRequest {
    /** Start of the date range to query, in `YYYY-MM-DD` format. Inclusive. */
    from: string;
    /** End of the date range to query, in `YYYY-MM-DD` format. Inclusive. */
    to: string;
    /** Filters metrics by the phone number associated with the click, in E.164 format. */
    phone?: string;
    /** Filters metrics by `utm_campaign` name. */
    utm_campaign?: string;
    /** Page number to retrieve. Default `1`. */
    page?: number;
    /** Number of records to return per page. Default `25`. */
    per_page?: number;
}
