// This file was auto-generated by Fern from our API Definition.

import * as Wavix from "../../../src/api/index";
import { WavixClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("SessionsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = [
            {
                created_at: "2022-02-16T13:41:38Z",
                session_id: "2953d4308f2e11ecb75fcdafd6d2d687",
                phone_number: "447919433768",
                destination_country: "GB",
                status: "verified",
                charge: "0.01",
                service_id: "7204a030201211ee9fb47d093f2f127c",
                service_name: "Wavix 2FA Service",
            },
            {
                created_at: "2022-02-16T13:41:38Z",
                session_id: "8753d4308f2e11ecb75fcdafd6d2d690",
                phone_number: "447919433768",
                destination_country: "GB",
                status: "pending",
                charge: "0.01",
                service_id: "7204a030201211ee9fb47d093f2f127c",
                service_name: "Wavix 2FA Service",
            },
        ];

        server
            .mockEndpoint()
            .get("/v1/two-fa/service/7204a030201211ee9fb47d093f2f127c/sessions")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.twoFa.sessions.list({
            service_id: "7204a030201211ee9fb47d093f2f127c",
            from: "2022-01-01",
            to: "2022-01-31",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/two-fa/service/service_id/sessions")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.twoFa.sessions.list({
                service_id: "service_id",
                from: "2023-01-15",
                to: "2023-01-15",
            });
        }).rejects.toThrow(Wavix.BadRequestError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/two-fa/service/service_id/sessions")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.twoFa.sessions.list({
                service_id: "service_id",
                from: "2023-01-15",
                to: "2023-01-15",
            });
        }).rejects.toThrow(Wavix.ForbiddenError);
    });

    test("list (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/two-fa/service/service_id/sessions")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.twoFa.sessions.list({
                service_id: "service_id",
                from: "2023-01-15",
                to: "2023-01-15",
            });
        }).rejects.toThrow(Wavix.NotFoundError);
    });
});
