// This file was auto-generated by Fern from our API Definition.

import * as Wavix from "../../../src/api/index";
import { WavixClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("VerificationClient", () => {
    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { service_id: "7204a030201211ee9fb47d093f2f127c", to: "447919433768", channel: "sms" };
        const rawResponseBody = {
            success: true,
            service_id: "7204a030201211ee9fb47d093f2f127c",
            session_url: "https://api.wavix.com/v1/two-fa/verification/2953d4308f2e11ecb75fcdafd6d2d687",
            session_id: "2953d4308f2e11ecb75fcdafd6d2d687",
            destination: "447919433768",
            created_at: "2022-02-16T13:41:38Z",
            number_lookup: { number_type: "mobile", country: "GB", current_carrier: "Vodafone" },
        };

        server
            .mockEndpoint()
            .post("/v1/two-fa/verification")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.twoFa.verification.create({
            service_id: "7204a030201211ee9fb47d093f2f127c",
            to: "447919433768",
            channel: "sms",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { service_id: "service_id", to: "to", channel: "channel" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/two-fa/verification")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.twoFa.verification.create({
                service_id: "service_id",
                to: "to",
                channel: "channel",
            });
        }).rejects.toThrow(Wavix.BadRequestError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { service_id: "service_id", to: "to", channel: "channel" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/two-fa/verification")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.twoFa.verification.create({
                service_id: "service_id",
                to: "to",
                channel: "channel",
            });
        }).rejects.toThrow(Wavix.ForbiddenError);
    });

    test("resend (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { channel: "sms" };
        const rawResponseBody = {
            success: true,
            channel: "voice",
            destination: "447919433768",
            created_at: "2022-02-16T13:41:38Z",
        };

        server
            .mockEndpoint()
            .post("/v1/two-fa/verification/2953d4308f2e11ecb75fcdafd6d2d687")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.twoFa.verification.resend({
            session_id: "2953d4308f2e11ecb75fcdafd6d2d687",
            channel: "sms",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("resend (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { channel: "sms" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/two-fa/verification/session_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.twoFa.verification.resend({
                session_id: "session_id",
                channel: "sms",
            });
        }).rejects.toThrow(Wavix.BadRequestError);
    });

    test("resend (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { channel: "sms" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/two-fa/verification/session_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.twoFa.verification.resend({
                session_id: "session_id",
                channel: "sms",
            });
        }).rejects.toThrow(Wavix.ForbiddenError);
    });

    test("check (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { code: "123456" };
        const rawResponseBody = { is_valid: true };

        server
            .mockEndpoint()
            .post("/v1/two-fa/verification/2953d4308f2e11ecb75fcdafd6d2d687/check")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.twoFa.verification.check({
            session_id: "2953d4308f2e11ecb75fcdafd6d2d687",
            code: "123456",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("check (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { code: "code" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/two-fa/verification/session_id/check")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.twoFa.verification.check({
                session_id: "session_id",
                code: "code",
            });
        }).rejects.toThrow(Wavix.BadRequestError);
    });

    test("check (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { code: "code" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/two-fa/verification/session_id/check")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.twoFa.verification.check({
                session_id: "session_id",
                code: "code",
            });
        }).rejects.toThrow(Wavix.ForbiddenError);
    });

    test("cancel (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { success: true };

        server
            .mockEndpoint()
            .patch("/v1/two-fa/verification/2953d4308f2e11ecb75fcdafd6d2d687/cancel")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.twoFa.verification.cancel({
            session_id: "2953d4308f2e11ecb75fcdafd6d2d687",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("cancel (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/v1/two-fa/verification/session_id/cancel")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.twoFa.verification.cancel({
                session_id: "session_id",
            });
        }).rejects.toThrow(Wavix.BadRequestError);
    });

    test("cancel (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/v1/two-fa/verification/session_id/cancel")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.twoFa.verification.cancel({
                session_id: "session_id",
            });
        }).rejects.toThrow(Wavix.ForbiddenError);
    });

    test("cancel (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/v1/two-fa/verification/session_id/cancel")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.twoFa.verification.cancel({
                session_id: "session_id",
            });
        }).rejects.toThrow(Wavix.NotFoundError);
    });
});
