// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface GetTokensRequest {
    /** The UUID of the widget token to retrieve. */
    id: string;
}
