// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         sip_trunk: "my-sip-trunk",
 *         payload: {
 *             "user_id": "42"
 *         },
 *         ttl: 3600
 *     }
 */
export interface WebRtcTokenCreateRequest {
    /** Name of the SIP trunk the token authenticates against. */
    sip_trunk: string;
    /** Arbitrary client-defined data to associate with the token. */
    payload?: Record<string, unknown> | null;
    /** Time to live in seconds. Pass `null` for no expiration. */
    ttl: number | null;
}
