// This file was auto-generated by Fern from our API Definition.

import * as Wavix from "../../../src/api/index";
import { WavixClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("OptOutsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            items: [
                { phone_number: "15551234567", sender_id: "MySender", created_at: "2024-01-15T10:30:00Z" },
                { phone_number: "15559876543", campaign_id: "C123456", created_at: "2024-01-16T14:45:00Z" },
            ],
            pagination: { current_page: 1, per_page: 25, total: 2, total_pages: 1 },
        };

        server
            .mockEndpoint()
            .get("/v3/messages/opt-outs")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.smsAndMms.optOuts.list({
            sender_id: "MySender",
            campaign_id: "C123456",
            created_after: "2024-01-01",
            created_before: "2024-12-31",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v3/messages/opt-outs")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.smsAndMms.optOuts.list();
        }).rejects.toThrow(Wavix.BadRequestError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v3/messages/opt-outs")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.smsAndMms.optOuts.list();
        }).rejects.toThrow(Wavix.ForbiddenError);
    });

    test("list (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v3/messages/opt-outs")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.smsAndMms.optOuts.list();
        }).rejects.toThrow(Wavix.UnprocessableEntityError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { opt_out: { number: "16419252149", sender_id: "15072429497" } };
        const rawResponseBody = { success: true };

        server
            .mockEndpoint()
            .post("/v3/messages/opt-outs")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.smsAndMms.optOuts.create({
            opt_out: {
                number: "16419252149",
                sender_id: "15072429497",
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { opt_out: { number: "number" } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v3/messages/opt-outs")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.smsAndMms.optOuts.create({
                opt_out: {
                    number: "number",
                },
            });
        }).rejects.toThrow(Wavix.BadRequestError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { opt_out: { number: "number" } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v3/messages/opt-outs")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.smsAndMms.optOuts.create({
                opt_out: {
                    number: "number",
                },
            });
        }).rejects.toThrow(Wavix.ForbiddenError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { opt_out: { number: "number" } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v3/messages/opt-outs")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.smsAndMms.optOuts.create({
                opt_out: {
                    number: "number",
                },
            });
        }).rejects.toThrow(Wavix.NotFoundError);
    });

    test("create (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { opt_out: { number: "number" } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v3/messages/opt-outs")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.smsAndMms.optOuts.create({
                opt_out: {
                    number: "number",
                },
            });
        }).rejects.toThrow(Wavix.UnprocessableEntityError);
    });
});
