// This file was auto-generated by Fern from our API Definition.

import type * as Wavix from "../../../../index.js";

/**
 * @example
 *     {
 *         voice_campaign: {
 *             callflow_id: 3212,
 *             caller_id: "13123310912",
 *             contact: "16729923812"
 *         }
 *     }
 */
export interface CreateVoiceCampaignsRequest {
    voice_campaign: Wavix.VoiceCampaignResponse;
}
