// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "fc34ba88-1eee-476e-b09e-dae63dc441e0"
 *     }
 */
export interface DeleteSenderIdsRequest {
    /** The unique ID of the Sender ID. */
    id: string;
}
