// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         brand_id: "brand_id",
 *         id: "id"
 *     }
 */
export interface GetBrandEvidenceRequest {
    /** The unique ID of the 10DLC Brand. */
    brand_id: string;
    /** The unique ID of the Brand evidence file. */
    id: string;
}
