// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         brand_id: "B6AI7PA"
 *     }
 */
export interface ListBrandEvidenceRequest {
    /** The unique ID of the 10DLC Brand. */
    brand_id: string;
}
