// This file was auto-generated by Fern from our API Definition.

import type * as core from "../../../../../../../core/index.js";

/**
 * @example
 *     {
 *         file: fs.createReadStream("/path/to/your/file"),
 *         brand_id: "B6AI7PA"
 *     }
 */
export interface UploadBrandEvidenceRequest {
    /** The unique ID of the 10DLC Brand. */
    brand_id: string;
    /** Evidence file to upload. Maximum size is 10 MB. */
    file: core.file.Uploadable;
}
