// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { EventsClient } from "../resources/events/client/Client.js";
import { SessionsClient } from "../resources/sessions/client/Client.js";
import { VerificationClient } from "../resources/verification/client/Client.js";

export declare namespace TwoFaClient {
    export type Options = BaseClientOptions;
}

export class TwoFaClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<TwoFaClient.Options>;
    protected _verification: VerificationClient | undefined;
    protected _sessions: SessionsClient | undefined;
    protected _events: EventsClient | undefined;

    constructor(options: TwoFaClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get verification(): VerificationClient {
        return (this._verification ??= new VerificationClient(this._options));
    }

    public get sessions(): SessionsClient {
        return (this._sessions ??= new SessionsClient(this._options));
    }

    public get events(): EventsClient {
        return (this._events ??= new EventsClient(this._options));
    }
}
