// This file was auto-generated by Fern from our API Definition.

/**
 * Represents a subscription that delivers 10DLC lifecycle events to a webhook URL.
 */
export interface CreateSubscriptionsResponse {
    /** Category of 10DLC events to subscribe to. One of `brand` (brand status changes), `campaign` (campaign status changes), or `number` (number provisioning changes). */
    subscription_category: string;
    /** Webhook URL that events in this category are delivered to. */
    url: string;
}
