// This file was auto-generated by Fern from our API Definition.

/**
 * The feature is disabled for the account.
 */
export interface AccountErrorResponse {
    /** Indicates whether the request was successful */
    success: boolean;
    /** Human-readable error description */
    message: string;
}
