// This file was auto-generated by Fern from our API Definition.

export interface AccountLimits {
    /** Maximum outbound call duration, in seconds */
    max_call_duration: number;
    /** Maximum number of concurrent outbound calls. */
    max_sip_channels: number;
    /** Maximum outbound call rate, in cents */
    max_call_rate: string;
}
