// This file was auto-generated by Fern from our API Definition.

/**
 * Permission level for an API key scope group.
 */
export interface ApiKeyScopePermission {
    /**
     * Permission level:
     * - `none`: no access
     * - `read`: GET only
     * - `write`: all methods (includes read)
     */
    allow?: ApiKeyScopePermission.Allow | undefined;
}

export namespace ApiKeyScopePermission {
    /**
     * Permission level:
     * - `none`: no access
     * - `read`: GET only
     * - `write`: all methods (includes read)
     */
    export const Allow = {
        None: "none",
        Read: "read",
        Write: "write",
    } as const;
    export type Allow = (typeof Allow)[keyof typeof Allow];
}
