// This file was auto-generated by Fern from our API Definition.

import type * as Wavix from "../index.js";

/**
 * API key details including IP restrictions and scope permissions.
 */
export interface ApiKey {
    /** API key ID. */
    id: number;
    /** API key label. */
    label: string;
    /** API key value. */
    value: string;
    /** Indicates whether the API key is active. */
    active: boolean;
    /**
     * Indicates whether IP restrictions are enabled. When enabled,
     *  the API key works only from IP addresses in `permitted_ips`.
     */
    restricted: boolean;
    /**
     * List of permitted IP addresses. If `restricted` is false,
     *  an empty list means no IP restrictions. If `restricted` is true,
     *   an empty list prevents all requests.
     */
    permitted_ips: string[];
    /**
     * When `true`, the key is restricted to the permissions defined in the
     * scope fields below. When `false`, the key has full access.
     */
    scopes_enabled: boolean;
    /** Timestamp of the most recent authenticated request made with this key. */
    last_used_at: string | null;
    /** View, buy, release, and configure phone numbers, browse inventory, and manage the cart. */
    numbers: Wavix.ApiKeyScopePermission | null;
    /** View, create, update, and delete SIP trunks and their settings. */
    trunks: Wavix.ApiKeyScopePermission | null;
    /** Access call records and active calls, and control live call actions such as starting, answering, ending, audio playback, DTMF, streaming, and transcription requests. */
    calls: Wavix.ApiKeyCallsScopePermission | null;
    /** Access message history and Sender IDs, send messages, manage opt-outs, and create or delete Sender IDs. */
    messages: Wavix.ApiKeyScopePermission | null;
    /** List, download, and delete call recordings. */
    recordings: Wavix.ApiKeyScopePermission | null;
    /** View campaign analytics and Sender ID or Brand status, schedule bulk voice or SMS campaigns, register Brands, and create short links. */
    campaigns: Wavix.ApiKeyScopePermission | null;
    /** View 2FA service details and verification logs, trigger OTPs by voice or SMS, and validate verification codes. */
    two_fa: Wavix.ApiKeyScopePermission | null;
    /** View number validation results and trigger single or bulk validation or HLR lookup requests. */
    validator: Wavix.ApiKeyScopePermission | null;
    /** List, create, and delete webhooks. */
    webhooks: Wavix.ApiKeyScopePermission | null;
    /** Manage widget tokens, including listing, viewing, creating, updating, and deleting them. */
    embeddable: Wavix.ApiKeyScopePermission | null;
    /** Access statements, balance, payment methods, usage reports, and billing settings, including payment method updates. */
    billing: Wavix.ApiKeyScopePermission | null;
    /** View and update account profile information and timezone. */
    account: Wavix.ApiKeyScopePermission | null;
    /** Manage subaccounts: list and view them, create, update, and suspend them. */
    subaccounts: Wavix.ApiKeyScopePermission | null;
    /** Creation date and time in ISO 8601 format. */
    created_at: string;
}
