// This file was auto-generated by Fern from our API Definition.

import type * as Wavix from "../index.js";

export interface AvailableNumberListResponse {
    /** Phone numbers available for purchase that match the search criteria. */
    dids: Wavix.AvailableNumber[];
    pagination: Wavix.Pagination;
}
