// This file was auto-generated by Fern from our API Definition.

/**
 * Phone number available for purchase.
 */
export interface AvailableNumber {
    /** Phone number ID. */
    id: number;
    /** One-time activation fee in USD. */
    activation_fee: string;
    /** Monthly fee in USD. */
    monthly_fee: string;
    /** Price per inbound minute in USD. */
    per_min: string;
    /** Maximum number of concurrent inbound calls. */
    channels: string;
    /** City where the phone number originates. */
    city: string;
    /** Country where the phone number originates. */
    country: string;
    /** Two-letter ISO country code. */
    country_short_name: string;
    /** Indicates whether CNAM can be activated. */
    cnam: boolean | null;
    /** Number of free inbound minutes. */
    free_min: number;
    /** Phone number in E.164 format. */
    number: string;
    /** Documents required to activate the phone number. */
    require_docs: number[];
    /**
     * Indicates whether the phone number can receive inbound
     *  SMS and MMS messages.
     */
    sms_enabled: boolean;
    /** Price per inbound SMS segment in USD. */
    sms_price: number;
    /** Indicates whether the number can be used as the Caller ID for local calls. */
    domestic_cli?: boolean | undefined;
}
