// This file was auto-generated by Fern from our API Definition.

import type * as Wavix from "../index.js";

export interface BillingTransactionListResponse {
    /** Indicates whether there are no transactions. */
    is_empty: boolean;
    /** List of transactions. */
    transactions: Wavix.FinancialTransaction[];
    pagination: Wavix.Pagination;
}
