// This file was auto-generated by Fern from our API Definition.

export interface BrandStatusUpdatedWebhook {
    /** Unique identifier of the 10DLC Brand. */
    brand_id: string;
    /** Current verification status of the 10DLC Brand. One of `SELF_DECLARED`, `UNVERIFIED`, `VERIFIED`, `VETTED_VERIFIED`, `REVIEW`, or `SUSPENDED`. `SELF_DECLARED` means the Brand registered without external verification; `UNVERIFIED` means verification has not yet succeeded; `VERIFIED` means the Brand passed standard verification; `VETTED_VERIFIED` means the Brand also passed third-party vetting; `REVIEW` means verification is in progress; `SUSPENDED` means the Brand is blocked from sending. */
    status: BrandStatusUpdatedWebhook.Status;
}

export namespace BrandStatusUpdatedWebhook {
    /** Current verification status of the 10DLC Brand. One of `SELF_DECLARED`, `UNVERIFIED`, `VERIFIED`, `VETTED_VERIFIED`, `REVIEW`, or `SUSPENDED`. `SELF_DECLARED` means the Brand registered without external verification; `UNVERIFIED` means verification has not yet succeeded; `VERIFIED` means the Brand passed standard verification; `VETTED_VERIFIED` means the Brand also passed third-party vetting; `REVIEW` means verification is in progress; `SUSPENDED` means the Brand is blocked from sending. */
    export const Status = {
        SelfDeclared: "SELF_DECLARED",
        Unverified: "UNVERIFIED",
        Verified: "VERIFIED",
        VettedVerified: "VETTED_VERIFIED",
        Review: "REVIEW",
        Suspended: "SUSPENDED",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
