// This file was auto-generated by Fern from our API Definition.

import type * as Wavix from "../index.js";

export interface Call {
    /** Call ID. Deprecated — use `id` instead. */
    uuid: string;
    /** Call ID. Alias of `uuid`. */
    id: string;
    direction?: Wavix.CallDirection | undefined;
    /**
     * Most recent lifecycle event for the call. One of:
     *
     * - `call_setup` — the call is being initiated.
     * - `ringing` — the destination is ringing.
     * - `early_media` — early media (such as ringback) is playing before answer.
     * - `answered` — the destination answered the call.
     * - `completed` — the call ended normally.
     * - `busy` — the destination was busy.
     * - `cancelled` — the call was cancelled before answer.
     * - `rejected` — the destination rejected the call.
     * - `on_call_event` — an in-call event occurred (see `event_payload`).
     */
    event_type: Call.EventType;
    /** Date and time of the latest event in ISO 8601 format. */
    event_time: string;
    /** Event-specific metadata. */
    event_payload: Wavix.OnCallEventPayload | null;
    /** Caller ID. */
    from: string;
    /** Destination number. */
    to: string;
    /** Date and time when the call started in ISO 8601 format. */
    call_started: string;
    /** Date and time when the call was answered in ISO 8601 format. */
    call_answered: string | null;
    /** Date and time when the call ended in ISO 8601 format. */
    call_completed: string | null;
    /** Indicates whether the call was answered by a machine. */
    machine_detected: boolean;
    /** Call metadata */
    tag: string;
}

export namespace Call {
    /**
     * Most recent lifecycle event for the call. One of:
     *
     * - `call_setup` — the call is being initiated.
     * - `ringing` — the destination is ringing.
     * - `early_media` — early media (such as ringback) is playing before answer.
     * - `answered` — the destination answered the call.
     * - `completed` — the call ended normally.
     * - `busy` — the destination was busy.
     * - `cancelled` — the call was cancelled before answer.
     * - `rejected` — the destination rejected the call.
     * - `on_call_event` — an in-call event occurred (see `event_payload`).
     */
    export const EventType = {
        CallSetup: "call_setup",
        Ringing: "ringing",
        EarlyMedia: "early_media",
        Answered: "answered",
        Completed: "completed",
        Busy: "busy",
        Cancelled: "cancelled",
        Rejected: "rejected",
        OnCallEvent: "on_call_event",
    } as const;
    export type EventType = (typeof EventType)[keyof typeof EventType];
}
