// This file was auto-generated by Fern from our API Definition.

import type * as Wavix from "../index.js";

export interface CallCreateResponse {
    /** Call ID. Deprecated — use `id` instead. */
    uuid?: string | undefined;
    /** Call ID. Alias of `uuid`. */
    id?: string | undefined;
    direction?: Wavix.CallDirection | undefined;
    /**
     * Most recent lifecycle event for the call. One of:
     *
     * - `call_setup` — the call is being initiated.
     * - `ringing` — the destination is ringing.
     * - `early_media` — early media (such as ringback) is playing before answer.
     * - `answered` — the destination answered the call.
     * - `completed` — the call ended normally.
     * - `busy` — the destination was busy.
     * - `cancelled` — the call was cancelled before answer.
     * - `rejected` — the destination rejected the call.
     * - `on_call_event` — an in-call event occurred (see `event_payload`).
     */
    event_type?: CallCreateResponse.EventType | undefined;
    /** Date and time of the latest event */
    event_time?: string | undefined;
    /** Event-specific data */
    event_payload?: (Wavix.OnCallEventPayload | null) | undefined;
    /** Caller ID */
    from?: string | undefined;
    /** Destination number */
    to?: string | undefined;
    /** Date and time when the call started */
    call_started?: string | undefined;
    /** Date and time when the call was answered */
    call_answered?: (string | null) | undefined;
    /** Date and time when the call ended */
    call_completed?: (string | null) | undefined;
    /** Indicates whether the call was answered by an answering machine */
    machine_detected?: boolean | undefined;
    /** Call metadata */
    tag?: string | undefined;
}

export namespace CallCreateResponse {
    /**
     * Most recent lifecycle event for the call. One of:
     *
     * - `call_setup` — the call is being initiated.
     * - `ringing` — the destination is ringing.
     * - `early_media` — early media (such as ringback) is playing before answer.
     * - `answered` — the destination answered the call.
     * - `completed` — the call ended normally.
     * - `busy` — the destination was busy.
     * - `cancelled` — the call was cancelled before answer.
     * - `rejected` — the destination rejected the call.
     * - `on_call_event` — an in-call event occurred (see `event_payload`).
     */
    export const EventType = {
        CallSetup: "call_setup",
        Ringing: "ringing",
        EarlyMedia: "early_media",
        Answered: "answered",
        Completed: "completed",
        Busy: "busy",
        Cancelled: "cancelled",
        Rejected: "rejected",
        OnCallEvent: "on_call_event",
    } as const;
    export type EventType = (typeof EventType)[keyof typeof EventType];
}
