// This file was auto-generated by Fern from our API Definition.

export interface CallWebhookListResponseItem {
    /** Type of call event the webhook subscribes to. One of `post-call` (delivered once after the call ends) or `on-call` (delivered for in-call events while the call is active). */
    event_type: CallWebhookListResponseItem.EventType;
    /** Webhook URL */
    url: string;
}

export namespace CallWebhookListResponseItem {
    /** Type of call event the webhook subscribes to. One of `post-call` (delivered once after the call ends) or `on-call` (delivered for in-call events while the call is active). */
    export const EventType = {
        PostCall: "post-call",
        OnCall: "on-call",
    } as const;
    export type EventType = (typeof EventType)[keyof typeof EventType];
}
