// This file was auto-generated by Fern from our API Definition.

/** Specifies the streaming type. Can be either `oneway` for unidirectional or `twoway` for bidirectional streaming. */
export const CallStreamType = {
    Oneway: "oneway",
    Twoway: "twoway",
} as const;
export type CallStreamType = (typeof CallStreamType)[keyof typeof CallStreamType];
