// This file was auto-generated by Fern from our API Definition.

import type * as Wavix from "../index.js";

export interface CallListResponse {
    /** List of calls */
    calls: Wavix.Call[];
    /** Indicates whether the request was successful. */
    success: boolean;
}
