// This file was auto-generated by Fern from our API Definition.

export interface CallControlValidationErrorResponse {
    /** Indicates whether the request was successful. Always `false` for this error. */
    success: boolean;
    /** Human-readable summary of the validation failure. */
    message: string;
    /**
     * Field-level validation messages, keyed by the offending request
     * field name (snake_case). Absent when the request body could not be
     * parsed at all (for example, malformed JSON).
     */
    errors?: Record<string, string> | undefined;
}
