// This file was auto-generated by Fern from our API Definition.

export interface CampaignStatusUpdatedWebhook {
    /** Unique identifier of a 10DLC Brand */
    brand_id: string;
    /** Unique identifier of a 10DLC Campaign */
    campaign_id: string;
    /**
     * Current status of the 10DLC Campaign. One of:
     *
     * - `REVIEW` — the campaign is under review.
     * - `APPROVED` — the campaign was approved and can send.
     * - `DECLINED` — the campaign was rejected during review.
     * - `DELETED` — the campaign was removed.
     * - `EXPIRED` — the campaign registration lapsed.
     * - `SUSPENDED` — the campaign is blocked from sending.
     * - `PORTED_OUT` — the campaign was migrated to another provider.
     */
    status: CampaignStatusUpdatedWebhook.Status;
}

export namespace CampaignStatusUpdatedWebhook {
    /**
     * Current status of the 10DLC Campaign. One of:
     *
     * - `REVIEW` — the campaign is under review.
     * - `APPROVED` — the campaign was approved and can send.
     * - `DECLINED` — the campaign was rejected during review.
     * - `DELETED` — the campaign was removed.
     * - `EXPIRED` — the campaign registration lapsed.
     * - `SUSPENDED` — the campaign is blocked from sending.
     * - `PORTED_OUT` — the campaign was migrated to another provider.
     */
    export const Status = {
        Review: "REVIEW",
        Approved: "APPROVED",
        Declined: "DECLINED",
        Deleted: "DELETED",
        Expired: "EXPIRED",
        Suspended: "SUSPENDED",
        PortedOut: "PORTED_OUT",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
