// This file was auto-generated by Fern from our API Definition.

import type * as Wavix from "../index.js";

export interface CartResponse {
    /** List of phone numbers in the cart. */
    dids: Wavix.AvailableNumber[];
    /** Document types required to activate phone numbers. */
    doc_types: Wavix.DocumentType[];
}
