// This file was auto-generated by Fern from our API Definition.

export interface CdrTranscriptionCompletedWebhook {
    /** Call UUID */
    uuid: string;
    /** Outcome of the transcription. One of `completed` (the transcript was produced) or `failed` (the transcription could not be produced). */
    status: CdrTranscriptionCompletedWebhook.Status;
}

export namespace CdrTranscriptionCompletedWebhook {
    /** Outcome of the transcription. One of `completed` (the transcript was produced) or `failed` (the transcription could not be produced). */
    export const Status = {
        Completed: "completed",
        Failed: "failed",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
