// This file was auto-generated by Fern from our API Definition.

import type * as Wavix from "../index.js";

/**
 * A CDR of a single call with call transcription
 */
export interface CdrWithTranscription {
    /** Who answered the call. Allowed values are `human`, `machine`. */
    answered_by?: (string | null) | undefined;
    /** Date and time of the call */
    date: string;
    /** ANI/From attribute of the call */
    from: string;
    /** DNIS/To attribute of the call */
    to: string;
    disposition: Wavix.CallDisposition;
    /** Duration of the call, in seconds */
    duration: number;
    /** Destination of the call. For outbound calls, it contains the country name and, optionally, a mobile carrier or city name. For inbound calls, the destination includes the user-defined SIP trunk name, SIP URI, or PSTN number that the call is forwarded to. */
    destination: string;
    /** Price per minute, in USD */
    per_minute: string;
    /** Total charge for the call, in USD */
    charge: string;
    /** System-generated login of a SIP trunk. For `placed` calls only. */
    sip_trunk?: (string | null) | undefined;
    /** PSTN forwarding price, in USD. For `received` calls only when forwarded to PSTN. */
    forward_fee?: string | undefined;
    /** Call ID. Deprecated — use `call_id` instead. */
    uuid: string;
    /** Call ID. Alias of `uuid`. */
    call_id: string;
    /** Parent call ID. Deprecated — use `parent_call_id` instead. */
    parent_uuid?: (string | null) | undefined;
    /** Parent call ID. Alias of `parent_uuid`. */
    parent_call_id?: (string | null) | undefined;
    transcription: Wavix.TranscriptionReference | null;
}
