// This file was auto-generated by Fern from our API Definition.

import type * as Wavix from "../index.js";

export interface CityListResponse {
    /** Cities available for the requested country or region. */
    cities: Wavix.City[];
}
