// This file was auto-generated by Fern from our API Definition.

export interface City {
    /** City ID. */
    id: number;
    /** City name. */
    name: string;
    /** Rate center. */
    area_code: number;
}
