// This file was auto-generated by Fern from our API Definition.

export interface DocumentType {
    /** Document type ID. */
    id: number;
    /** Document type name. */
    name: string;
    /** Human-readable document type name. */
    title: string;
}
