// This file was auto-generated by Fern from our API Definition.

/**
 * Document type required to activate a phone number. One of: `id` - any form of ID,
 * `address` - proof of address, `localaddress` - proof of local address within the country.
 */
export const DocumentType = {
    Id: "id",
    Address: "address",
    Localaddress: "localaddress",
} as const;
export type DocumentType = (typeof DocumentType)[keyof typeof DocumentType];
