// This file was auto-generated by Fern from our API Definition.

export interface FileTranscriptionCompletedWebhook {
    /** Transcription request ID */
    request_id: string;
    /** Outcome of the transcription. One of `completed` (the transcript was produced) or `failed` (the transcription could not be produced). */
    status: string;
    /** A human-readable error description, if any */
    error: string | null;
}
