// This file was auto-generated by Fern from our API Definition.

import type * as Wavix from "../index.js";

export interface FileTranscriptionResponse {
    /** Complete transcription text attributed to each channel. */
    transcript: Wavix.FileTranscriptResponse | null;
    /** List of transcription turns, including speaker attribution, timestamps, and sentiment. */
    turns: Wavix.FileTranscriptTurn[] | null;
    /** Transcription request ID. */
    request_id: string;
    /** Transcription language. */
    language: FileTranscriptionResponse.Language;
    /** File duration in seconds. */
    duration: number | null;
    /** Total transcription charge in USD. */
    charge: string;
    /** Transcription status. Possible values are `completed`, `failed`. */
    status: FileTranscriptionResponse.Status;
    /** Date and time of the transcription in ISO 8601 format. */
    transcription_date: string;
    /** Conversation sentiment score. Scores from 1.0 to 3.0 are negative; scores from 4.0 to 5.0 are positive. */
    transcription_score: string | null;
    /** Transcription summary. */
    transcription_summary: string | null;
    /** Uploaded file URL. */
    original_file: string;
}

export namespace FileTranscriptionResponse {
    /** Transcription language. */
    export const Language = {
        En: "en",
        De: "de",
        Es: "es",
        Fr: "fr",
        It: "it",
    } as const;
    export type Language = (typeof Language)[keyof typeof Language];
    /** Transcription status. Possible values are `completed`, `failed`. */
    export const Status = {
        Completed: "completed",
        Failed: "failed",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
