// This file was auto-generated by Fern from our API Definition.

/**
 * Transcription `turn` details, including speaker, timestamps, text, and sentiment.
 */
export interface FileTranscriptTurn {
    /** Speaker identifier. */
    speaker: string;
    /** Turn start time in milliseconds from the beginning of the file. */
    s: number;
    /** Turn end time in milliseconds from the beginning of the file. */
    e: number;
    /** Transcription text attributed to the speaker. */
    text: string;
    /** Sentiment associated with the turn. Possible values are `positive`, `neutral`, `negative`. */
    sentiment: string;
}
