// This file was auto-generated by Fern from our API Definition.

export interface ForbiddenErrorResponse {
    /** Indicates whether the request was successful. Always `false` for this error. */
    success?: boolean | undefined;
    /** Human-readable description of why access is forbidden. */
    message?: string | undefined;
}
