// This file was auto-generated by Fern from our API Definition.

import type * as Wavix from "../index.js";

/**
 * An inbound message
 */
export interface InboundMessage {
    /** Unique identifier of the message generated by the platform */
    message_id: string;
    /** Sender ID used to send the message. Can be numeric or alphanumeric. */
    from: string;
    /** Phone number on the account that received the message. */
    to: string;
    message_body: Wavix.MessageBody;
    /** Timestamp the messages is received by Wavix */
    received_at: string;
}
