// This file was auto-generated by Fern from our API Definition.

import type * as Wavix from "../index.js";

export interface InvoiceListResponse {
    /** Indicates whether the statement list is empty. */
    is_empty: boolean;
    /** Auto-generated statements for the account. */
    invoices: Wavix.Invoice[];
    pagination: Wavix.Pagination;
}
