// This file was auto-generated by Fern from our API Definition.

import type * as Wavix from "../index.js";

export interface MessageResponse {
    /** Message ID. */
    message_id: string;
    /** Message type. Possible values are `sms`, `mms`. */
    message_type: string;
    /** Sender ID. */
    from: string;
    /** Recipient phone number. */
    to: string;
    /** Message direction. Possible values are `outbound`, `inbound`. */
    direction: string;
    /** Mobile country code. */
    mcc: string | null;
    /** Mobile network code. */
    mnc: string | null;
    message_body: Wavix.MessageBody;
    /** Tag to group messages, such as for a specific campaign. */
    tag: string | null;
    status: Wavix.MessageDeliveryStatus;
    /** Number of SMS segments. Always 1 for MMS. */
    segments: number;
    /** Total charge for the message in USD. */
    charge: string;
    /** Date and time the message was accepted in ISO 8601 format. */
    submitted_at: string;
    /** Date and time the message was sent in ISO 8601 format. For mobile-terminated messages only. */
    sent_at: string | null;
    /**
     * Date and time the message was delivered in ISO 8601 format. Refers to DLR reception for mobile-terminated messages
     *  or webhook relay for mobile-originated messages.
     */
    delivered_at: string | null;
    /** Human-readable error message. */
    error_message: string | null;
    /** Mobile carrier fees in USD. */
    carrier_fees?: (string | null) | undefined;
}
