// This file was auto-generated by Fern from our API Definition.

import type * as Wavix from "../index.js";

/**
 * Message delivery report (DLR).
 */
export interface MessagesDeliveryReport {
    /** Message ID. */
    message_id: string;
    /** Type of message. Possible values are `sms`, `mms`. */
    message_type: string;
    /** Sender ID. Can be numeric or alphanumeric. */
    from: string;
    /** Destination phone number. */
    to: string;
    /** Tag to identify a group of messages, such as those associated with a campaign. */
    tag?: (string | null) | undefined;
    status: Wavix.MessageDeliveryStatus;
    /** Number of message segments for SMS. For MMS, the value is always 1. */
    segments_count: number;
    /** Date and time the message was accepted in ISO 8601 format. */
    sent: string | null;
    /** Date and time when the final status was received in ISO 8601 format. */
    delivered?: (string | null) | undefined;
    /** Human-readable error description. */
    error?: (string | null) | undefined;
    /** Total charge for the message in USD. */
    charge: string;
    /** Mobile carrier fees in USD. */
    carrier_fees: string;
}
