// This file was auto-generated by Fern from our API Definition.

export interface NumberStatusUpdatedWebhook {
    /** 10DLC Brand ID. */
    brand_id: string;
    /** 10DLC Campaign ID. */
    campaign_id: string;
    /** Phone number associated with a 10DLC Campaign. */
    number: string;
    /** Status of the phone number's assignment to the 10DLC Campaign. One of `APPROVED` (the number is registered to the campaign), `PENDING` (registration is in progress), or `REJECTED` (registration was declined). */
    status: NumberStatusUpdatedWebhook.Status;
}

export namespace NumberStatusUpdatedWebhook {
    /** Status of the phone number's assignment to the 10DLC Campaign. One of `APPROVED` (the number is registered to the campaign), `PENDING` (registration is in progress), or `REJECTED` (registration was declined). */
    export const Status = {
        Approved: "APPROVED",
        Pending: "PENDING",
        Rejected: "REJECTED",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
