// This file was auto-generated by Fern from our API Definition.

import type * as Wavix from "../index.js";

/**
 * Inbound call destination
 */
export interface NumberDestination {
    /** SIP URI, PSTN number, or SIP trunk login for inbound call routing. */
    destination: string;
    /** Destination priority (lower is higher priority). */
    priority: number;
    transport: Wavix.InboundCallTransport;
    /** SIP trunk ID when `transport` is 5, otherwise null. */
    trunk_id?: (number | null) | undefined;
}
