// This file was auto-generated by Fern from our API Definition.

import type * as Wavix from "../index.js";

export type NumberValidatorCreateBulkResponse =
    | Wavix.PhoneValidationBatchResponse
    /**
     * Returned when validation runs asynchronously; poll results using `request_id`. */
    | {
          request_id?: string | undefined;
      };
