// This file was auto-generated by Fern from our API Definition.

/**
 * Payload for the `on_call_event` event type.
 */
export interface OnCallEventPayload {
    /** Type of in-call sub-event. One of `audio` (audio playback progress) or `collect` (DTMF digit collection progress). */
    type: OnCallEventPayload.Type;
    /**
     * Sub-event-specific data. Structure depends on the `type` field:
     * - `audio`: `{ "status": "started" | "completed", "playback_id": "<uuid>" }`
     * - `collect`: `{ "digits": "<digits>", "status": "started" | "completed" | "failed" }`
     */
    payload?: (Record<string, unknown> | null) | undefined;
}

export namespace OnCallEventPayload {
    /** Type of in-call sub-event. One of `audio` (audio playback progress) or `collect` (DTMF digit collection progress). */
    export const Type = {
        Audio: "audio",
        Collect: "collect",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
