// This file was auto-generated by Fern from our API Definition.

import type * as Wavix from "../index.js";

export interface OptOutsListResponse {
    /** Opt-out records that match the request. */
    items?: Wavix.OptOutItem[] | undefined;
    pagination?: Wavix.Pagination | undefined;
}
