// This file was auto-generated by Fern from our API Definition.

export interface OptOutItem {
    /** Opted-out phone number. */
    phone_number?: string | undefined;
    /** Sender ID. Contains `null` if the phone number opted out of all messages. */
    sender_id?: (string | null) | undefined;
    /** 10DLC campaign ID, if any. */
    campaign_id?: (string | null) | undefined;
    /** Opt-out date and time in ISO 8601 format. */
    created_at?: string | undefined;
}
