// This file was auto-generated by Fern from our API Definition.

/** Depth of validation to perform on the phone number. One of `format` (checks number syntax only), `analysis` (returns number metadata such as type and country), or `validation` (performs a live network lookup of the number's current status). */
export const PhoneNumberValidationType = {
    Format: "format",
    Analysis: "analysis",
    Validation: "validation",
} as const;
export type PhoneNumberValidationType = (typeof PhoneNumberValidationType)[keyof typeof PhoneNumberValidationType];
