// This file was auto-generated by Fern from our API Definition.

/**
 * Number validator response details.
 */
export interface PhoneValidationResultResponse {
    /** Phone number. */
    phone_number: string;
    /** Indicates whether the phone number is valid. */
    valid: boolean;
    /** Phone number country code in ISO 3166-1 alpha-2 format. `null` if the number is invalid. */
    country_code: string | null;
    /** Phone number in international E.164 format. */
    e164_format: string;
    /** Phone number in the national format of the identified country. */
    national_format: string;
    /** Indicates whether the phone number is ported. `null` if the phone number is invalid. */
    ported?: (boolean | null) | undefined;
    /** Mobile Country Code (MCC). Applies to mobile numbers only. `null` if the phone number is invalid. */
    mcc?: (string | null) | undefined;
    /** Mobile Network Code (MNC). Applies to mobile numbers only. `null` if the phone number is invalid. */
    mnc?: (string | null) | undefined;
    /** Phone number type. Allowed values: `mobile`, `landline`, `toll-free`. `null` if the phone number is invalid. */
    number_type?: (string | null) | undefined;
    /** Carrier name. `null` if the phone number is invalid. */
    carrier_name?: (string | null) | undefined;
    /** Indicates whether the phone number belongs to a range associated with traffic pumping. `null` if the phone number is invalid. */
    risky_destination?: (boolean | null) | undefined;
    /**
     * Indicates whether the phone number belongs to an unallocated range.
     *  `null` if the phone number is invalid.
     */
    unallocated_range?: (boolean | null) | undefined;
    /** Indicates whether the number is registered in a mobile network. Applies to mobile numbers only.  `null` if the phone number is invalid. */
    reachable?: (boolean | null) | undefined;
    /**
     * Indicates whether the number is roaming. Applies to mobile numbers only.
     *  `null` if the phone number is invalid.
     */
    roaming?: (boolean | null) | undefined;
    /** Time zone identified based on the country and area code.  `null` if the phone number is invalid. */
    timezone?: (string | null) | undefined;
    /** Charge for the validation. */
    charge: string;
    /**
     * Result code for the validation. `000` indicates success. Possible values:
     * - `013` — internal service error, uncategorized.
     * - `021` — invalid phone number length or format.
     * - `041` — remote timeout.
     * - `042` — remote query failed.
     * - `091` — insufficient funds.
     */
    error_code: string;
}
