// This file was auto-generated by Fern from our API Definition.

import type * as Wavix from "../index.js";

export interface PhoneValidationBatchResponse {
    /** Validation request status. */
    status: string;
    /** Number of validations still in progress. */
    pending: number;
    /** Total number of phone numbers in the request. */
    count: number;
    /** List of validation results for each phone number. */
    items: Wavix.PhoneValidationResultResponse[];
}
