// This file was auto-generated by Fern from our API Definition.

export interface PhoneLookupDetails {
    /** The destination phone number type */
    number_type: string;
    /** The destination phone number's 2-letter ISO country code */
    country: string;
    /** The carrier name the phone number currently belongs to */
    current_carrier: string;
}
