// This file was auto-generated by Fern from our API Definition.

export interface RecordingDeletedErrorResponse {
    /** Indicates whether the request was successful. Always `false` for this error. */
    success: boolean;
    /** Error flag. Always `true` for this error. */
    error?: boolean | undefined;
    /** Human-readable explanation of why the recording is unavailable. */
    message: string;
    /** Timestamp when the recording was deleted, in ISO 8601 format. */
    deleted_at?: string | undefined;
}
