// This file was auto-generated by Fern from our API Definition.

import type * as Wavix from "../index.js";

export interface SenderIdDetails {
    /** Sender ID ID. */
    id: string;
    /** Sender ID name. */
    sender_id: string;
    type: Wavix.SenderIdType;
    /** List of countries where the Sender ID is allowlisted. */
    allowlisted_in: string[];
    /** Primary use case declared for the Sender ID, such as `transactional`, `promo`, or `authentication`. */
    usecase?: string | undefined;
    /** Message samples. */
    samples?: string[] | undefined;
}
