// This file was auto-generated by Fern from our API Definition.

import type * as Wavix from "../index.js";

export interface SenderIdListResponse {
    /** List of Sender IDs. */
    items: Wavix.SenderId[];
}
