// This file was auto-generated by Fern from our API Definition.

export interface SenderIdResponse {
    /** Sender ID ID. */
    id: string;
    /** Sender ID. */
    sender_id: string;
    /** Format of the Sender ID. One of `alphanumeric` (a text sender name), `numeric` (a phone number), or `shortcode` (a short code). */
    type: SenderIdResponse.Type;
    /** Use case for the Sender ID. */
    usecase?: string | undefined;
    /** Message samples. */
    samples?: string[] | undefined;
    /** List of countries where the Sender ID is allowlisted. */
    allowlisted_in?: string[] | undefined;
}

export namespace SenderIdResponse {
    /** Format of the Sender ID. One of `alphanumeric` (a text sender name), `numeric` (a phone number), or `shortcode` (a short code). */
    export const Type = {
        Alphanumeric: "alphanumeric",
        Numeric: "numeric",
        Shortcode: "shortcode",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
