// This file was auto-generated by Fern from our API Definition.

import type * as Wavix from "../index.js";

export interface ShortLinkMetricsResponse {
    /** List of short link metrics matching search criteria. */
    metrics: Wavix.ShortLinkMetricsItem[];
    pagination: Wavix.Pagination;
}
