// This file was auto-generated by Fern from our API Definition.

import type * as Wavix from "../index.js";

export interface SipTrunkListResponse {
    /** SIP trunks associated with the account. */
    sip_trunks: Wavix.SipTrunkSummary[] | null;
    pagination: Wavix.Pagination;
}
