// This file was auto-generated by Fern from our API Definition.

export interface SipTrunkCreateRequest {
    /** User-defined name of the SIP trunk */
    label: string;
    /** Password set for the SIP trunk. A strong password helps keep the trunk secure. */
    password: string;
    /** For SIP trunks with IP authentication, includes the SIP endpoint public static IP address and the status of the authentication request. Wavix authenticates all SIP traffic originating from this IP address. */
    host_request?: SipTrunkCreateRequest.HostRequest | undefined;
    /** Caller ID associated with the SIP trunk. Must be an active or verified number on the account. */
    callerid: string;
    /** Indicates whether any active or verified phone number on the account can be used as the Caller ID for the SIP trunk. */
    multiple_numbers?: boolean | undefined;
    /** Indicates whether SIP trunk registration is allowed from only specific public static IP addresses. When set to `true`, the `allowed_ips` parameter must be provided. */
    ip_restrict: boolean;
    /** A list of public static IP addresses allowed to register with the SIP trunk */
    allowed_ips?: (SipTrunkCreateRequest.AllowedIps.Item[] | null) | undefined;
    /** Indicates whether inbound calls include dialed number information in the `To` header of SIP INVITE requests */
    didinfo_enabled: boolean;
    /** Indicates whether a maximum call duration limit is enforced for the SIP trunk */
    call_restrict: boolean;
    /** Maximum call duration for the SIP trunk, in seconds. Must not exceed the maximum duration set for the account. Ignored when `call_restrict` is `false`. */
    call_limit?: number | undefined;
    /** Indicates if the max cost limit for an outbound call limit is activated for the SIP trunk. */
    cost_limit: boolean;
    /** Maximum cost for an outbound call, in USD */
    max_call_cost?: number | undefined;
    /** Indicates whether a limit on the number of concurrent outbound calls is enforced for the SIP trunk */
    channels_restrict: boolean;
    /** Maximum number of concurrent outbound calls for the SIP trunk. Must not exceed the outbound channel capacity set for the account. Ignored when `channels_restrict` is `false`. */
    max_channels?: number | undefined;
    /** Indicates whether a custom dial plan is activated for the SIP trunk */
    rewrite_enabled: boolean;
    /** Digits to automatically prepend to each dialed phone number */
    rewrite_prefix?: string | undefined;
    /** Number of leading digits to automatically remove from each dialed phone number */
    rewrite_cond?: string | undefined;
    /** Indicates whether outbound call recording is enabled for the SIP trunk */
    call_recording_enabled?: boolean | undefined;
    /**
     * Indicates whether automatic call transcription is enabled for the SIP trunk.
     * Available for `Flex Pro` customers only.
     */
    transcription_enabled: boolean;
    /**
     * Transcriptions will be generated for calls that meet or exceed the specified minimal call duration threshold, in seconds.
     * Available for `Flex Pro` customers only.
     */
    transcription_threshold: number;
    /**
     * Indicates whether automatic voicemail detection is enabled for the SIP trunk.
     * Available for `Flex Pro` customers only.
     */
    machine_detection_enabled?: boolean | undefined;
    /** Indicates whether SRTP media encryption is enabled for the SIP trunk. */
    encrypted_media?: boolean | undefined;
}

export namespace SipTrunkCreateRequest {
    /**
     * For SIP trunks with IP authentication, includes the SIP endpoint public static IP address and the status of the authentication request. Wavix authenticates all SIP traffic originating from this IP address.
     */
    export interface HostRequest {
        /** SIP endpoint public static IP address */
        host: string;
    }

    export type AllowedIps = AllowedIps.Item[];

    export namespace AllowedIps {
        export interface Item {
            /** Public static IP address allowed to register with the SIP trunk. */
            ip: string;
        }
    }
}
