// This file was auto-generated by Fern from our API Definition.

import type * as Wavix from "../index.js";

export interface SubAccountsTransactionsListResponse {
    /** Financial transactions for the subaccount. */
    transactions?: SubAccountsTransactionsListResponse.Transactions.Item[] | undefined;
    pagination?: Wavix.Pagination | undefined;
}

export namespace SubAccountsTransactionsListResponse {
    export type Transactions = Transactions.Item[];

    export namespace Transactions {
        export interface Item {
            /** Transaction amount. */
            amount?: number | undefined;
            /** Sub-account balance after the transaction. */
            balance_after?: number | undefined;
            /** Transaction date and time in ISO 8601 format. */
            date?: string | undefined;
            /** Transaction details. */
            details?: string | undefined;
            /** Transaction status. */
            status?: string | undefined;
            /** Transaction type. */
            type?: number | undefined;
        }
    }
}
