// This file was auto-generated by Fern from our API Definition.

export interface SubmitFileTranscriptionResponse {
    /** Uploaded file name. */
    file: string;
    /** Transcription request ID. */
    request_id: string;
    /** Indicates whether the request was successful. */
    success: boolean;
}
