// This file was auto-generated by Fern from our API Definition.

export interface TcrErrorMessage {
    /** TCR error code */
    code: string;
    /** A human-readable error description */
    message: string;
}
