// This file was auto-generated by Fern from our API Definition.

import type * as Wavix from "../index.js";

export interface TenDlcCampaignNumberListResponse {
    /** Unique identifier of the 10DLC Brand that owns the Campaign. */
    brand_id: string;
    /** Unique identifier of the 10DLC Campaign the numbers belong to. */
    campaign_id: string;
    /** Phone numbers assigned to the Campaign, with their provisioning status. */
    numbers: Wavix.TenDlcCampaignNumber[];
}
