// This file was auto-generated by Fern from our API Definition.

/**
 * 10DLC Brand registration request
 */
export type TenDlcBrandCreateRequest =
    /**
     * PUBLIC_PROFIT brands must provide stock_symbol and stock_exchange. */
    | {
          entity_type?: "PUBLIC_PROFIT" | undefined;
      }
    /**
     * Non-PUBLIC_PROFIT brands must not include stock_symbol or stock_exchange. */
    | {
          entity_type?: ("PRIVATE_PROFIT" | "NON_PROFIT" | "GOVERNMENT") | undefined;
          stock_symbol?: (unknown | null) | undefined;
          stock_exchange?: (unknown | null) | undefined;
      };
