// This file was auto-generated by Fern from our API Definition.

import type * as Wavix from "../index.js";

export interface TenDlcBrandAppeal {
    /** A list of Brand Identity status appeal categories associated with the original request */
    categories: string[];
    /** The date and time the appeal request is created */
    created_at: string;
    /** A list of evidence UUIDs to be associated with the appeal */
    evidence: string[];
    /** The appeal outcome details */
    outcome: TenDlcBrandAppeal.Outcome;
    /** The appeal status */
    status: string;
    /** The date and time the appeal request is updated */
    updated_at: string;
    /** The appeal justification */
    explanation: string;
}

export namespace TenDlcBrandAppeal {
    /**
     * The appeal outcome details
     */
    export interface Outcome {
        /** An optional attributes that might be returned from TCR */
        optional_attributes: Record<string, unknown>;
        /** Brand Identity Verification appeal outcome */
        vetting_status: Outcome.VettingStatus;
        /** Brand Identity Verification appeal feedback, if any */
        feedback: Outcome.Feedback;
    }

    export namespace Outcome {
        /** Brand Identity Verification appeal outcome */
        export const VettingStatus = {
            Review: "REVIEW",
            Verified: "VERIFIED",
            Unverified: "UNVERIFIED",
            VettedVerified: "VETTED_VERIFIED",
            Suspended: "SUSPENDED",
        } as const;
        export type VettingStatus = (typeof VettingStatus)[keyof typeof VettingStatus];

        /**
         * Brand Identity Verification appeal feedback, if any
         */
        export interface Feedback {
            /** The feedback category */
            category: Wavix.TcrFeedbackCategory[];
        }
    }
}
