// This file was auto-generated by Fern from our API Definition.

/**
 * Identity verification status of the 10DLC Brand. One of:
 *
 * - `REVIEW` — verification is in progress.
 * - `VERIFIED` — the Brand passed standard verification.
 * - `UNVERIFIED` — verification has not succeeded.
 * - `VETTED_VERIFIED` — the Brand also passed third-party vetting.
 * - `SUSPENDED` — the Brand is blocked from sending.
 */
export const TenDlcBrandIdentityVerificationStatus = {
    Review: "REVIEW",
    Verified: "VERIFIED",
    Unverified: "UNVERIFIED",
    VettedVerified: "VETTED_VERIFIED",
    Suspended: "SUSPENDED",
} as const;
export type TenDlcBrandIdentityVerificationStatus =
    (typeof TenDlcBrandIdentityVerificationStatus)[keyof typeof TenDlcBrandIdentityVerificationStatus];
