// This file was auto-generated by Fern from our API Definition.

/** Legal entity type of the 10DLC Brand. One of `PRIVATE_PROFIT` (privately held for-profit company), `PUBLIC_PROFIT` (publicly traded for-profit company), `NON_PROFIT` (non-profit organization), or `GOVERNMENT` (government entity). */
export const TenDlcBrandEntityType = {
    PrivateProfit: "PRIVATE_PROFIT",
    PublicProfit: "PUBLIC_PROFIT",
    NonProfit: "NON_PROFIT",
    Government: "GOVERNMENT",
} as const;
export type TenDlcBrandEntityType = (typeof TenDlcBrandEntityType)[keyof typeof TenDlcBrandEntityType];
