// This file was auto-generated by Fern from our API Definition.

export interface TenDlcBrandVettingAppealOutcome {
    /** Current status of the Brand vetting */
    vet_status: string;
    /** The Brand vetting score */
    vet_score: number;
    /** The feedback provided by the external vetting provider */
    feedback: TenDlcBrandVettingAppealOutcome.Feedback;
}

export namespace TenDlcBrandVettingAppealOutcome {
    /**
     * The feedback provided by the external vetting provider
     */
    export interface Feedback {
        /** An list of human-readable explanations returned by TCR */
        reasons: string[];
    }
}
