// This file was auto-generated by Fern from our API Definition.

import type * as Wavix from "../index.js";

/**
 * A list of 10DLC Brands
 */
export interface TenDlcBrandListResponse {
    /** A paginated list of 10DLC Brands matching the filter criteria */
    items: Wavix.TenDlcBrand[];
    /** Pagination details */
    pagination: TenDlcBrandListResponse.Pagination;
}

export namespace TenDlcBrandListResponse {
    /**
     * Pagination details
     */
    export interface Pagination {
        /** Current page number. */
        current_page: number;
        /** Number of records per page. */
        per_page: number;
        /** Total number of records. */
        total: number;
        /** Total number of pages. */
        total_pages: number;
    }
}
