// This file was auto-generated by Fern from our API Definition.

export interface TenDlcCampaignNumber {
    /** Phone number assigned to the 10DLC Campaign, in E.164 format. */
    number: string;
    /** Provisioning status of the phone number, such as `APPROVED`. Only `APPROVED` numbers can be used as Sender IDs. */
    status: string;
}
