// This file was auto-generated by Fern from our API Definition.

import type * as Wavix from "../index.js";

/**
 * Represents a 10DLC brand registered for application-to-person messaging. A Brand identifies the business behind one or more messaging campaigns.
 */
export interface TenDlcBrand {
    /** Unique identifier of the Brand assigned by the registry. */
    brand_id: string;
    /** Doing-business-as name, or the public-facing brand name. */
    dba_name: string;
    /** Registered legal name of the company that owns the Brand. */
    company_name: string;
    /** Company entity type. */
    entity_type: Wavix.TenDlcBrandEntityType;
    /** Industry vertical the Brand operates in. */
    vertical: string;
    /** IRS Employer Identification Number (EIN) or other tax ID of the company. */
    ein_taxid: string;
    /** ISO 3166-1 alpha-2 country code where the Tax ID was issued. */
    ein_taxid_country: string;
    /** Brand identity verification status. */
    status: Wavix.TenDlcBrandIdentityVerificationStatus;
    /** Business website URL. */
    website?: (string | null) | undefined;
    /** Stock ticker symbol of the company. Required for publicly traded companies. */
    stock_symbol?: (string | null) | undefined;
    /** Code of the stock exchange the company is listed on. Required for publicly traded companies. */
    stock_exchange?: (string | null) | undefined;
    /** Business contact first name. */
    first_name: string;
    /** Business contact last name. */
    last_name: string;
    /** Support contact phone number in E.164 format. */
    phone_number: string;
    /** Support contact email address. */
    email: string;
    /** Street address of the business. */
    street_address: string;
    /** City of the business address. */
    city: string;
    /** State or province of the business address. */
    state_or_province?: (string | null) | undefined;
    /** ISO 3166-1 alpha-2 country code of the business address. */
    country: string;
    /** ZIP or postal code of the business address. */
    zip: string;
    /** Feedback from the identity verification process explaining the current `status`. */
    feedback: string | null;
    /** Indicates whether the Brand is a mock brand for testing. */
    mock?: boolean | undefined;
    /** Timestamp when the Brand was created, in ISO 8601 format. */
    created_at: string;
    /** Timestamp when the Brand was last updated, in ISO 8601 format. */
    updated_at: string;
}
