// This file was auto-generated by Fern from our API Definition.

/**
 * Represents the result of an external vetting performed on a 10DLC brand. Vetting can raise a Brand's trust score and unlock higher messaging throughput.
 */
export interface TenDlcBrandVetting {
    /** Code identifying the external vetting provider that performed the vetting. */
    evp_id: string;
    /** Timestamp when the vetting request was created, in ISO 8601 format. */
    create_date: string;
    /** Additional provider-specific details about the vetting request. */
    vetting_details?: Record<string, unknown> | undefined;
    /** Timestamp when the vetting was completed, in ISO 8601 format. Null while the vetting is still in progress. */
    vetted_date: string | null;
    /** Unique identifier of the vetting request. */
    vetting_id: string;
    /** Token issued by the vetting provider that uniquely identifies this vetting result. */
    vetting_token: string | null;
    /** Score assigned to the Brand by the vetting provider. Null until vetting completes. */
    vetting_score: number | null;
    /** Class of vetting performed, such as `STANDARD` or `ENHANCED`. */
    vetting_class: string;
    /** Current status of the vetting request, such as `PENDING` or `ACTIVE`. */
    vetting_status: string;
    /** Reasons explaining the assigned `vetting_score`. Null when no reasons are provided. */
    reasons: string[] | null;
}
