// This file was auto-generated by Fern from our API Definition.

/**
 * Brand identity verification appeal details.
 */
export interface TenDlcBrandAppealCreateRequest {
    /** List of appeal categories. Allowed values: `VERIFY_TAX_ID`, `VERIFY_NON_PROFIT`, `VERIFY_GOVERNMENT` */
    appeal_categories: string[];
    /** List of evidence IDs associated with the appeal. */
    evidence: string[];
    /** Appeal comment or justification. */
    explanation?: string | undefined;
}
