// This file was auto-generated by Fern from our API Definition.

export interface TooManyRequestsErrorResponse {
    /** Indicates whether the request was successful. Always `false` for this error. */
    success: boolean;
    /** Human-readable description stating that the rate limit was exceeded. */
    message: string;
}
