// This file was auto-generated by Fern from our API Definition.

/** Language of the transcription, as a two-letter ISO 639-1 code. One of `en` (English), `de` (German), `es` (Spanish), `fr` (French), or `it` (Italian). `null` lets the platform auto-detect the language. */
export const TranscriptionLanguage = {
    En: "en",
    De: "de",
    Es: "es",
    Fr: "fr",
    It: "it",
} as const;
export type TranscriptionLanguage = (typeof TranscriptionLanguage)[keyof typeof TranscriptionLanguage];
