// This file was auto-generated by Fern from our API Definition.

/**
 * Represents a single turn in a call transcript. Each turn carries the text attributed to one speaker, with the start and end times for that text.
 */
export interface TranscriptTurn {
    /** Phone number of the speaker attributed to this turn, in E.164 format. */
    type?: string | undefined;
    /** Start of the `turn`, in milliseconds. The start time is calculated from the moment the call was answered. */
    s?: number | undefined;
    /** End of the `turn`, in milliseconds. The end time is calculated from the moment the call was answered. */
    e?: number | undefined;
    /** Transcribed text attributed to the speaker for this turn. */
    text?: string | undefined;
    /** Sentiment detected in the speaker's text for this turn, such as `neutral`, `positive`, or `negative`. */
    sentiment?: string | undefined;
}
