// This file was auto-generated by Fern from our API Definition.

/** Current status of the transaction. One of `Created` (the transaction was created but not yet processed), `Pending` (the transaction is being processed), `Committed` (the transaction was applied to the balance), or `Reverted` (the transaction was rolled back). */
export const TransactionStatus = {
    Created: "Created",
    Pending: "Pending",
    Committed: "Committed",
    Reverted: "Reverted",
} as const;
export type TransactionStatus = (typeof TransactionStatus)[keyof typeof TransactionStatus];
