// This file was auto-generated by Fern from our API Definition.

export interface TranscriptionFilter {
    /** Search in an agent's spoken words and phrases */
    agent: TranscriptionFilter.Agent;
    /** Search in an customer's spoken words and phrases */
    client: TranscriptionFilter.Client;
    /** Search in both speakers' spoken words and phrases */
    any: TranscriptionFilter.Any;
}

export namespace TranscriptionFilter {
    /**
     * Search in an agent's spoken words and phrases
     */
    export interface Agent {
        /** Only calls with transcription that includes all of the specified keywords and phrases are returned. The listed keywords and phrases are combined using logical AND */
        must?: string[] | undefined;
        /** Only calls with transcription that includes any of the specified keywords and phrases are returned. The listed keywords and phrases are combined using logical OR */
        match?: string[] | undefined;
        /** Only calls with transcription that does not include any of the specified keywords and phrases are returned. The listed keywords and phrases are combined using logical OR */
        exclude?: string[] | undefined;
    }

    /**
     * Search in an customer's spoken words and phrases
     */
    export interface Client {
        /** Only calls with transcription that includes all of the specified keywords and phrases are returned. The listed keywords and phrases are combined using logical AND */
        must?: string[] | undefined;
        /** Only calls with transcription that includes any of the specified keywords and phrases are returned. The listed keywords and phrases are combined using logical OR */
        match?: string[] | undefined;
        /** Only calls with transcription that does not include any of the specified keywords and phrases are returned. The listed keywords and phrases are combined using logical OR */
        exclude?: string[] | undefined;
    }

    /**
     * Search in both speakers' spoken words and phrases
     */
    export interface Any {
        /** Only calls with transcription that includes all of the specified keywords and phrases are returned. The listed keywords and phrases are combined using logical AND */
        must?: string[] | undefined;
        /** Only calls with transcription that includes any of the specified keywords and phrases are returned. The listed keywords and phrases are combined using logical OR */
        match?: string[] | undefined;
        /** Only calls with transcription that does not include any of the specified keywords and phrases are returned. The listed keywords and phrases are combined using logical OR */
        exclude?: string[] | undefined;
    }
}
