// This file was auto-generated by Fern from our API Definition.

/** Outcome of the transcription. One of `completed` (the transcript was produced) or `failed` (the transcription could not be produced). */
export const TranscriptionStatus = {
    Completed: "completed",
    Failed: "failed",
} as const;
export type TranscriptionStatus = (typeof TranscriptionStatus)[keyof typeof TranscriptionStatus];
