// This file was auto-generated by Fern from our API Definition.

/** Language used for text-to-speech synthesis. One of `ru` (Russian), `en` (English), `sp` (Spanish), or `ge` (German). */
export const TtsLanguage = {
    Ru: "ru",
    En: "en",
    Sp: "sp",
    Ge: "ge",
} as const;
export type TtsLanguage = (typeof TtsLanguage)[keyof typeof TtsLanguage];
