// This file was auto-generated by Fern from our API Definition.

export interface TwoFactorVerificationCheckResponse {
    /** Indicates whether the entered code is valid */
    is_valid: boolean;
}
