// This file was auto-generated by Fern from our API Definition.

import type * as Wavix from "../index.js";

export interface TwoFactorVerificationResponse {
    /** Indicates whether the 2FA Verification was successfully created */
    success: boolean;
    /** Unique identifier of the Wavix 2FA Service */
    service_id: string;
    /** Automatically generated 2FA Verification URL. The URL can be used to resend or validate the OTP. */
    session_url: string;
    /** Unique identifier of the Wavix 2FA Verification */
    session_id: string;
    /** The end user's phone number. */
    destination: string;
    /** Date and time the 2FA Verification is created */
    created_at: string;
    number_lookup: Wavix.PhoneLookupDetails;
}
