// This file was auto-generated by Fern from our API Definition.

export interface UnprocessableEntityErrorBody {
    /** Indicates whether the request was successful. Always `false` for this error. */
    success: boolean;
    /** Human-readable error description */
    message: string;
}
