// This file was auto-generated by Fern from our API Definition.

export interface UnprocessableEntityErrorBody {
    /** Human-readable error description. */
    error?: string | undefined;
    /** Numbers from the cart that could not be purchased. */
    error_dids?: string[] | undefined;
}
