// This file was auto-generated by Fern from our API Definition.

export interface ValidationErrorResponse {
    /** Indicates whether the request was successful. Always `false` for this error. */
    success?: boolean | undefined;
    /** Human-readable description naming the missing or invalid request parameter. */
    message?: string | undefined;
}
