// This file was auto-generated by Fern from our API Definition.

export interface VoiceCampaignsGetResponse {
    voice_campaign?: VoiceCampaignsGetResponse.VoiceCampaign | undefined;
}

export namespace VoiceCampaignsGetResponse {
    export interface VoiceCampaign {
        /** Unique identifier of the voice campaign. */
        id?: number | undefined;
        /** Current status of the voice campaign, such as `in_progress`. */
        status?: string | undefined;
        /** Timestamp when the voice campaign was created, in ISO 8601 format. */
        timestamp?: string | undefined;
        /** Phone number used as the Caller ID for the outbound call, in E.164 format. */
        caller_id?: string | undefined;
        /** Destination phone number the outbound call is placed to, in E.164 format. */
        contact?: string | undefined;
    }
}
