// This file was auto-generated by Fern from our API Definition.

import type * as Wavix from "../index.js";

export interface VoiceCampaignCreateRequest {
    voice_campaign: Wavix.VoiceCampaignResponse;
}
