// This file was auto-generated by Fern from our API Definition.

import type * as Wavix from "../index.js";

/**
 * Paginated list of WebRTC tokens.
 */
export interface WebRtcTokensListResponse {
    /** WebRTC tokens on the current page. */
    items?: Wavix.WebRtcToken[] | undefined;
    pagination?: Wavix.Pagination | undefined;
}
