// This file was auto-generated by Fern from our API Definition.

export interface WebRtcTokenResponse {
    /** Signed JWT used by the Wavix embeddable widget to authenticate. */
    token: string;
    /** Unique identifier of the WebRTC token. */
    uuid: string;
    /** Name of the SIP trunk the token authenticates against. */
    sip_trunk: string;
    /** Arbitrary client-defined data associated with the token. */
    payload?: (Record<string, unknown> | null) | undefined;
    /** Lifetime of the token, in seconds. `null` means the token does not expire. */
    ttl?: (number | null) | undefined;
}
