// This file was auto-generated by Fern from our API Definition.

export interface WhatsAppMessage {
    /** Message ID. */
    uuid: string;
    /** Sender's phone number in E.164 digits. */
    from: string;
    /** Recipient's phone number in E.164 digits. */
    to: string;
    /** Message delivery status. */
    status: WhatsAppMessage.Status;
    /** Template used to send the message. */
    template?: (WhatsAppMessage.Template | null) | undefined;
    /** Date and time the message was created, in ISO 8601 format. */
    created_at: string;
}

export namespace WhatsAppMessage {
    /** Message delivery status. */
    export const Status = {
        Failed: "failed",
        Sent: "sent",
        Delivered: "delivered",
        Undelivered: "undelivered",
        Expired: "expired",
        Rejected: "rejected",
        Unknown: "unknown",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];

    /**
     * Template used to send the message.
     */
    export interface Template {
        /** Template name. */
        name?: string | undefined;
        /** Template language code. */
        language?: string | undefined;
    }
}
