// This file was auto-generated by Fern from our API Definition.

import type * as Wavix from "../index.js";

export interface WhatsAppMessageListResponse {
    /** Messages that match the request. */
    messages: Wavix.WhatsAppMessageListItem[];
    pagination: Wavix.Pagination;
}
