// This file was auto-generated by Fern from our API Definition.

/**
 * One structural component (header, body, footer, or buttons) of a WhatsApp message template.
 */
export interface WhatsAppTemplateComponent {
    /** Component type. */
    type: WhatsAppTemplateComponent.Type;
    /** Header content format. Present on `HEADER` components only. */
    format?: WhatsAppTemplateComponent.Format | undefined;
    /** Component text, with `{{n}}` placeholders where applicable. */
    text?: string | undefined;
    /** Sample values for the component's placeholders, in the shape the provider expects. */
    example?: Record<string, unknown> | undefined;
    /** Button definitions. Present on `BUTTONS` components only. */
    buttons?: Record<string, unknown>[] | undefined;
}

export namespace WhatsAppTemplateComponent {
    /** Component type. */
    export const Type = {
        Header: "HEADER",
        Body: "BODY",
        Footer: "FOOTER",
        Buttons: "BUTTONS",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
    /** Header content format. Present on `HEADER` components only. */
    export const Format = {
        Text: "TEXT",
        Image: "IMAGE",
        Video: "VIDEO",
        Document: "DOCUMENT",
        Location: "LOCATION",
    } as const;
    export type Format = (typeof Format)[keyof typeof Format];
}
