// This file was auto-generated by Fern from our API Definition.

import type * as Wavix from "../index.js";

export interface WhatsAppTemplate {
    /** Template ID. */
    uuid: string;
    /** Template name. */
    name: string;
    /** Template language code. */
    language: string;
    /** Template category. */
    category: WhatsAppTemplate.Category;
    /** Template review/approval status. */
    status: WhatsAppTemplate.Status;
    /** Template's messaging quality rating. */
    quality_rating?: (WhatsAppTemplate.QualityRating | null) | undefined;
    /** Date and time the template was submitted for review, in ISO 8601 format. */
    submitted_at?: (string | null) | undefined;
    /** Structural components of the template. */
    components: Wavix.WhatsAppTemplateComponent[];
    /** Date and time the template was created, in ISO 8601 format. */
    created_at: string;
}

export namespace WhatsAppTemplate {
    /** Template category. */
    export const Category = {
        Marketing: "marketing",
        Authentication: "authentication",
        Utility: "utility",
    } as const;
    export type Category = (typeof Category)[keyof typeof Category];
    /** Template review/approval status. */
    export const Status = {
        Draft: "draft",
        Pending: "pending",
        Approved: "approved",
        Rejected: "rejected",
        Paused: "paused",
        Flagged: "flagged",
        Disabled: "disabled",
        InAppeal: "in_appeal",
        PendingDeletion: "pending_deletion",
        Deleted: "deleted",
        Unknown: "unknown",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
    /** Template's messaging quality rating. */
    export const QualityRating = {
        High: "high",
        Medium: "medium",
        Low: "low",
        Unknown: "unknown",
    } as const;
    export type QualityRating = (typeof QualityRating)[keyof typeof QualityRating];
}
