// This file was auto-generated by Fern from our API Definition.

import type * as Wavix from "../index.js";

export interface WhatsAppTemplateCreateRequest {
    /** Template name. */
    name: string;
    /** Template language code. */
    language: string;
    /** Template category. */
    category: WhatsAppTemplateCreateRequest.Category;
    /** Structural components of the template. Must include a `BODY` component. */
    components: Wavix.WhatsAppTemplateComponent[];
}

export namespace WhatsAppTemplateCreateRequest {
    /** Template category. */
    export const Category = {
        Marketing: "marketing",
        Authentication: "authentication",
        Utility: "utility",
    } as const;
    export type Category = (typeof Category)[keyof typeof Category];
}
