// This file was auto-generated by Fern from our API Definition.

export interface WhatsAppMessageListItem {
    /** Message ID. */
    uuid: string;
    /** Message direction. */
    direction: WhatsAppMessageListItem.Direction;
    /** Message delivery status. */
    status: WhatsAppMessageListItem.Status;
    /** For `outbound` messages, the sender's phone number. For `inbound`, the originating phone number. */
    from: string;
    /** For `outbound` messages, the recipient's phone number. For `inbound`, the sender's phone number. */
    to: string;
    /** Recipient's country, derived from the phone number. */
    country?: (string | null) | undefined;
    /** Date and time the message was created, in ISO 8601 format. */
    created_at: string;
}

export namespace WhatsAppMessageListItem {
    /** Message direction. */
    export const Direction = {
        Outbound: "outbound",
        Inbound: "inbound",
    } as const;
    export type Direction = (typeof Direction)[keyof typeof Direction];
    /** Message delivery status. */
    export const Status = {
        Failed: "failed",
        Sent: "sent",
        Delivered: "delivered",
        Undelivered: "undelivered",
        Expired: "expired",
        Rejected: "rejected",
        Unknown: "unknown",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
