// This file was auto-generated by Fern from our API Definition.

export interface WhatsAppMessageSendRequest {
    /** Sender's phone number, 6-20 digits. */
    from: string;
    /** Recipient's phone number, 6-20 digits. */
    to: string;
    template: WhatsAppMessageSendRequest.Template;
}

export namespace WhatsAppMessageSendRequest {
    export interface Template {
        /** Approved template name. */
        name: string;
        /** Template language code. */
        language: string;
        /** Values substituted into the template body's `{{n}}` placeholders, in order. */
        placeholders?: string[] | undefined;
        /** Header content, required only when the template's `HEADER` component needs one. */
        header?: Template.Header | undefined;
        /** Dynamic values for the template's `BUTTONS` component, one entry per button, matching the template's button order. */
        buttons?: Template.Buttons.Item[] | undefined;
    }

    export namespace Template {
        /**
         * Header content, required only when the template's `HEADER` component needs one.
         */
        export interface Header {
            type?: Header.Type | undefined;
            /** Value for a `TEXT` header's `{{1}}` placeholder. */
            placeholder?: string | undefined;
            /** Media URL for an `IMAGE`/`VIDEO`/`DOCUMENT` header. */
            mediaUrl?: string | undefined;
            /** Filename for a `DOCUMENT` header. */
            filename?: string | undefined;
            /** Latitude for a `LOCATION` header. */
            latitude?: number | undefined;
            /** Longitude for a `LOCATION` header. */
            longitude?: number | undefined;
            /** Placeholder name for a named-parameter `TEXT` header. */
            parameterName?: string | undefined;
            /** Value for a named-parameter `TEXT` header. */
            text?: string | undefined;
        }

        export namespace Header {
            export const Type = {
                Text: "TEXT",
                TextNamedParameters: "TEXT_NAMED_PARAMETERS",
                Image: "IMAGE",
                Video: "VIDEO",
                Document: "DOCUMENT",
                Location: "LOCATION",
            } as const;
            export type Type = (typeof Type)[keyof typeof Type];
        }

        export type Buttons = Buttons.Item[];

        export namespace Buttons {
            export interface Item {
                type: Item.Type;
                /** Accepts any additional properties */
                [key: string]: any;
            }

            export namespace Item {
                export const Type = {
                    QuickReply: "QUICK_REPLY",
                    Url: "URL",
                    CopyCode: "COPY_CODE",
                    Flow: "FLOW",
                    Catalog: "CATALOG",
                    MultiProduct: "MULTI_PRODUCT",
                    OrderDetails: "ORDER_DETAILS",
                    VoiceCall: "VOICE_CALL",
                } as const;
                export type Type = (typeof Type)[keyof typeof Type];
            }
        }
    }
}
