// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         country_id: 1891
 *     }
 */
export interface ListCitiesRequest {
    /** The unique ID of the country. */
    country_id: number;
    /** When `true`, returns only cities that offer text-enabled numbers. */
    text_enabled_only?: boolean;
}
