// This file was auto-generated by Fern from our API Definition.

import * as Wavix from "../../../src/api/index";
import { WavixClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("CountriesClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            countries: [
                { id: 8669, name: "Argentina", has_provinces_or_states: false },
                { id: 8650, name: "Australia", has_provinces_or_states: true },
            ],
        };

        server.mockEndpoint().get("/v1/buy/countries").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.buy.countries.list();
        expect(response).toEqual(rawResponseBody);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/v1/buy/countries").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.buy.countries.list();
        }).rejects.toThrow(Wavix.ForbiddenError);
    });
});
