// This file was auto-generated by Fern from our API Definition.

import type * as Wavix from "../../../../index.js";

/**
 * @example
 *     {
 *         call_id: "bbaa37bf-430a-46da-ade3-c248e407016"
 *     }
 */
export interface CdrRetranscriptionRequest {
    /** The unique ID of the call. */
    call_id: string;
    language?: Wavix.TranscriptionLanguage;
    /** Webhook URL to receive status updates. */
    webhook_url?: string;
}
