// This file was auto-generated by Fern from our API Definition.

import type * as Wavix from "../../../../index.js";

/**
 * @example
 *     {
 *         type: "placed",
 *         from: "2023-08-01",
 *         to: "2023-08-31"
 *     }
 */
export interface CdrSearchRequest {
    /** Filters by call type. One of `placed` (outbound calls dialed by the account) or `received` (inbound calls answered by the account). */
    type: CdrSearchRequest.Type;
    /** Start date for call search in `YYYY-MM-DD` format. */
    from: string;
    /** End date for call search in `YYYY-MM-DD` format. */
    to: string;
    /** Originating phone number to filter results. Accepts full or partial number. */
    from_search?: string;
    /** Destination phone number to filter results. Accepts full or partial number. */
    to_search?: string;
    /** SIP trunk login to filter outbound calls. Ignored for inbound calls. */
    sip_trunk?: string;
    /** Minimum call duration in seconds. */
    min_duration?: number;
    transcription?: Wavix.TranscriptionFilter;
    /** Call ID. */
    uuid?: string;
    /**
     * Call disposition to filter results.  If omitted, returns only answered
     *  calls. Allowed values: `answered`, `noanswer`, `busy`,
     *   `failed`, `all`. Use `all` to return calls
     *    regardless of their disposition.
     */
    disposition?: Wavix.CallDisposition;
    /** Page number to retrieve. */
    page?: number;
    /** Number of records per page. */
    per_page?: number;
}

export namespace CdrSearchRequest {
    /** Filters by call type. One of `placed` (outbound calls dialed by the account) or `received` (inbound calls answered by the account). */
    export const Type = {
        Placed: "placed",
        Received: "received",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
