// This file was auto-generated by Fern from our API Definition.

import type * as Wavix from "../../../../index.js";

/**
 * @example
 *     {
 *         from: "2023-01-01",
 *         to: "2023-09-01",
 *         type: "received",
 *         from_search: "13524815863",
 *         to_search: "12565378257",
 *         sip_trunk: "12321",
 *         uuid: "99df5ffd-962a-410f-bcce-d08f1f7f328c",
 *         page: 1,
 *         per_page: 25
 *     }
 */
export interface ListAllCdrsRequest {
    /** Start of the date range to query, in `YYYY-MM-DD` format. Inclusive. */
    from: string;
    /** End of the date range to query, in `YYYY-MM-DD` format. Inclusive. */
    to: string;
    /** Filters CDRs by call direction. One of `placed` (outbound calls dialed by the account) or `received` (inbound calls answered by the account). */
    type: string;
    /** Filters CDRs by call disposition. One of `answered` (the called party answered), `busy` (the called party was busy), `rejected` (the call was declined), `failed` (the call could not be routed), or `all` (no disposition filter). */
    disposition?: Wavix.CallDisposition;
    /** Filters CDRs by originating phone number. Accepts a full or partial number. */
    from_search?: string;
    /** Filters CDRs by destination phone number. Accepts a full or partial number. */
    to_search?: string;
    /** Filters outbound CDRs by SIP trunk login. Ignored for inbound calls. */
    sip_trunk?: string;
    /** Filters CDRs by the unique call ID. */
    uuid?: string;
    /** Page number to retrieve. Default `1`. */
    page?: number;
    /** Number of records to return per page. Default `25`. */
    per_page?: number;
}
