// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: 123
 *     }
 */
export interface GetSubAccountsRequest {
    /** The unique ID of the sub-account. */
    id: number;
}
