// This file was auto-generated by Fern from our API Definition.

import type * as Wavix from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface ListSubAccountsRequest {
    /** Filters sub-accounts by status. One of `enabled` (the sub-account is active) or `disabled` (the sub-account is suspended). */
    status?: Wavix.ListSubAccountsRequestStatus;
}
