// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: 123,
 *         name: "Updated Company Name",
 *         status: "enabled",
 *         default_destinations: {
 *             sms_endpoint: "https://examples.com/sms",
 *             dlr_endpoint: "https://examples.com/dlr"
 *         }
 *     }
 */
export interface SubAccountsUpdateRequest {
    /** The unique ID of the sub-account. */
    id: number;
    /** Sub-account name. */
    name: string;
    /** Status of the subaccount. One of `enabled` (the subaccount is active and can be used) or `disabled` (the subaccount is suspended). */
    status?: SubAccountsUpdateRequest.Status;
    /** Default webhook URLs for inbound messages and delivery reports. */
    default_destinations?: SubAccountsUpdateRequest.DefaultDestinations;
}

export namespace SubAccountsUpdateRequest {
    /** Status of the subaccount. One of `enabled` (the subaccount is active and can be used) or `disabled` (the subaccount is suspended). */
    export const Status = {
        Enabled: "enabled",
        Disabled: "disabled",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];

    /**
     * Default webhook URLs for inbound messages and delivery reports.
     */
    export interface DefaultDestinations {
        /** Inbound messages webhook URL. */
        sms_endpoint?: string | undefined;
        /** Delivery report webhook URL. */
        dlr_endpoint?: string | undefined;
    }
}
