// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         dids: "47832123321,47832123324,478321233215"
 *     }
 */
export interface DeleteNumbersRequest {
    /** Record IDs of the phone numbers to release. Mutually exclusive with `dids`. */
    ids?: number | number[];
    /** Comma-separated phone numbers to release. Mutually exclusive with `ids`. */
    dids?: string;
}
