// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: 123
 *     }
 */
export interface GetNumbersRequest {
    /** The unique ID of the phone number. */
    id: number;
}
