// This file was auto-generated by Fern from our API Definition.

import type * as Wavix from "../../../../index.js";

/**
 * @example
 *     {
 *         ids: [123, 456]
 *     }
 */
export interface NumberBulkUpdateRequest {
    /**
     * Numbers (by ID) to apply the patch to. The same patch is
     * applied to every listed number.
     */
    ids: number[];
    /** Indicates whether SMS is enabled for the phone numbers. */
    sms_enabled?: boolean;
    /** Inbound call routing destinations for the phone numbers. */
    destinations?: Wavix.NumberDestination[];
    /** Callback URL for inbound messages. */
    sms_relay_url?: string;
    /** Indicates whether call recording is enabled. */
    call_recording_enabled?: boolean;
    /** Indicates whether call transcription is enabled. */
    transcription_enabled?: boolean;
    /** Minimum call duration in seconds before transcription runs. */
    transcription_threshold?: number;
    /** Callback URL for call status updates. */
    call_status_url?: string;
}
