// This file was auto-generated by Fern from our API Definition.

import type * as Wavix from "../../../../index.js";

/**
 * @example
 *     {
 *         id: 123
 *     }
 */
export interface NumberUpdateRequest {
    /** The unique ID of the phone number. */
    id: number;
    /** Indicates whether SMS is enabled for the phone number. */
    sms_enabled?: boolean;
    /** Inbound call routing destinations for the phone number. */
    destinations?: Wavix.NumberDestination[];
    /** Callback URL for inbound messages. */
    sms_relay_url?: string;
    /** Indicates whether call recording is enabled. */
    call_recording_enabled?: boolean;
    /** Indicates whether call transcription is enabled. */
    transcription_enabled?: boolean;
    /** Minimum call duration in seconds before transcription runs. */
    transcription_threshold?: number;
    /** Callback URL for call status updates. */
    call_status_url?: string;
}
