// This file was auto-generated by Fern from our API Definition.

import type * as Wavix from "../../../../../../index.js";

/**
 * @example
 *     {
 *         from_date: "2023-08-01",
 *         to_date: "2023-08-31",
 *         details_contains: "monthly",
 *         payments: true,
 *         page: 1,
 *         per_page: 25
 *     }
 */
export interface ListTransactionsRequest {
    /** Start of the date range to query, in `YYYY-MM-DD` format. Inclusive. */
    from_date: string;
    /** End of the date range to query, in `YYYY-MM-DD` format. Inclusive. */
    to_date: string;
    /** Filters transactions by type. Accepts a `TransactionType` value. */
    type?: Wavix.TransactionType;
    /** Filters transactions whose `details` contain the given substring. */
    details_contains?: string;
    /** When `true`, returns only account top-up transactions. Defaults to all transaction types. */
    payments?: boolean;
    /** Page number to retrieve. Default `1`. */
    page?: number;
    /** Number of records to return per page. Default `25`. */
    per_page?: number;
}
