// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         call_id: "call_id",
 *         id: "id"
 *     }
 */
export interface DeleteStreamsRequest {
    /** The `uuid` of the call. */
    call_id: string;
    /** The `uuid` of the media stream to stop. */
    id: string;
}
