// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         brand_id: "BMQFB7X"
 *     }
 */
export interface ListBrandVettingAppealsRequest {
    /** The unique ID of the 10DLC Brand. */
    brand_id: string;
}
