// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         brand_id: "B6AI7PA",
 *         appeal_categories: ["VERIFY_TAX_ID"],
 *         evidence: ["855dff49-c097-4645-3983-08dcb9856232"]
 *     }
 */
export interface TenDlcBrandVettingAppealCreateRequest {
    /** The unique ID of the 10DLC Brand. */
    brand_id: string;
    /** List of appeal categories. Allowed values: `VERIFY_TAX_ID`, `VERIFY_NON_PROFIT`, `VERIFY_GOVERNMENT`, `LOW_SCORE`. */
    appeal_categories: string[];
    /** List of evidence IDs associated with the appeal. */
    evidence: string[];
    /** Appeal comment or justification. */
    explanation?: string;
    /** EVP ID. */
    evp_id?: string;
    /** Vetting ID. */
    vetting_id?: string;
}
