// This file was auto-generated by Fern from our API Definition.

import * as Wavix from "../../../src/api/index";
import { WavixClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("MetricsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            metrics: [
                {
                    latitude: 59.3247,
                    longitude: 18.056,
                    operating_system: "Mac OS X 10.15",
                    browser: "Firefox",
                    language: "English",
                    phone: "12762025555",
                    utm_campaign: "summer",
                    created_at: "2023-07-19 18:23:42.120Z",
                    link_hash: "hd82Jhs21",
                    user_id: 100017,
                },
            ],
            pagination: { current_page: 2, per_page: 25, total: 101, total_pages: 5 },
        };

        server
            .mockEndpoint()
            .get("/v1/short-links/metrics")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.linkShortener.metrics.list({
            from: "2023-05-01",
            to: "2023-05-31",
            phone: "1872025555",
            utm_campaign: "summer",
            page: 1,
            per_page: 25,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/short-links/metrics")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.linkShortener.metrics.list({
                from: "2023-01-15",
                to: "2023-01-15",
            });
        }).rejects.toThrow(Wavix.BadRequestError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/short-links/metrics")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.linkShortener.metrics.list({
                from: "2023-01-15",
                to: "2023-01-15",
            });
        }).rejects.toThrow(Wavix.ForbiddenError);
    });
});
