// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         ids: ["541139862174", "541139862175"]
 *     }
 */
export interface RemoveCartRequest {
    /** Phone numbers to remove from the cart. */
    ids: string[];
}
