// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         brand_id: "BM20QP9",
 *         campaign_id: "CKLCK95"
 *     }
 */
export interface GetCampaignsRequest {
    /** The unique ID of the 10DLC Brand. */
    brand_id: string;
    /** The unique ID of the 10DLC Campaign. */
    campaign_id: string;
}
