// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         brand_id: "B9FXYNH",
 *         campaign_id: "CSJ4TV0",
 *         nudge_intent: "REVIEW",
 *         description: "Please review the campaign."
 *     }
 */
export interface NudgeCampaignsRequest {
    /** The unique ID of the 10DLC Brand. */
    brand_id: string;
    /** The unique ID of the 10DLC Campaign. */
    campaign_id: string;
    /**
     * Nudge intent. Allowed values: `REVIEW`, `APPEAL_REJECTION`.
     * Use `nudge_intent` to specify the action: - `REVIEW`: Request review for a pending Campaign. - `APPEAL_REJECTION`: Appeal a rejected Campaign.
     */
    nudge_intent: string;
    /** Description of the nudge request. */
    description: string;
}
