// This file was auto-generated by Fern from our API Definition.

import * as Wavix from "../../../src/api/index";
import { WavixClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("TranscriptionClient", () => {
    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            transcript: { "16572026750": "", "16465292513": "" },
            turns: [
                { type: "46844685344", s: 160, e: 7280, text: "Hello, how can I help you?", sentiment: "neutral" },
                {
                    type: "+16572026750",
                    s: 2400,
                    e: 3280,
                    text: "Hello, I have a question about my bill.",
                    sentiment: "neutral",
                },
            ],
            uuid: "e84f350f-6da7-4b56-80eb-41dec572626b",
            language: "en",
            duration: 102,
            charge: "0.01",
            status: "completed",
            transcription_date: "2023-01-09T10:04:39Z",
            call_date: "2023-01-09T10:01:13Z",
            call_uuid: "bbaa37bf-430a-46da-ade3-c248e4070161",
            call_score: "3.8",
            call_summary: "The agent and client discussed billing issues.",
        };

        server
            .mockEndpoint()
            .get("/v1/cdrs/bbaa37bf-430a-46da-ade3-c248e407016/transcription")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.cdrs.transcription.get({
            call_id: "bbaa37bf-430a-46da-ade3-c248e407016",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/cdrs/call_id/transcription")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.cdrs.transcription.get({
                call_id: "call_id",
            });
        }).rejects.toThrow(Wavix.ForbiddenError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/cdrs/call_id/transcription")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.cdrs.transcription.get({
                call_id: "call_id",
            });
        }).rejects.toThrow(Wavix.NotFoundError);
    });
});
