// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         sender_id: "MySender",
 *         campaign_id: "C123456",
 *         created_after: "2024-01-01",
 *         created_before: "2024-12-31"
 *     }
 */
export interface ListOptOutsRequest {
    /** Filters opt-outs by the Sender ID they apply to. */
    sender_id?: string;
    /** Filters opt-outs by the 10DLC campaign ID they apply to. */
    campaign_id?: string;
    /** Returns opt-outs created on or after this date, in `YYYY-MM-DD` format. */
    created_after?: string;
    /** Returns opt-outs created on or before this date, in `YYYY-MM-DD` format. */
    created_before?: string;
    /** Page number to retrieve. Minimum `1`, default `1`. */
    page?: number;
    /** Number of records to return per page. Default `25`, maximum `100`. */
    per_page?: number;
}
