// This file was auto-generated by Fern from our API Definition.

import type * as Wavix from "../../../../../../index.js";

/**
 * @example
 *     {
 *         opt_out: {
 *             number: "16419252149",
 *             sender_id: "15072429497"
 *         }
 *     }
 */
export interface OptOutCreateRequest {
    opt_out: Wavix.OptOut;
}
