// This file was auto-generated by Fern from our API Definition.

import type * as Wavix from "../../../../../../index.js";

/**
 * @example
 *     {
 *         sent_after: "2023-04-10",
 *         sent_before: "2023-04-13",
 *         type: "outbound",
 *         from: "15072429497",
 *         to: "16419252149",
 *         tag: "campaignX",
 *         page: 2,
 *         per_page: 50
 *     }
 */
export interface ListMessagesRequest {
    /** Returns messages sent on or after this date, in `YYYY-MM-DD` format. */
    sent_after?: string;
    /** Returns messages sent on or before this date, in `YYYY-MM-DD` format. */
    sent_before?: string;
    /** Filters messages by direction. One of `inbound` (messages received by the account) or `outbound` (messages sent by the account). */
    type: string;
    /** Filters by message sender. For `outbound` messages, the Sender ID used to send the message; for `inbound` messages, the originating phone number. */
    from?: string;
    /** Filters by message recipient. For `outbound` messages, the destination phone number; for `inbound` messages, an SMS-enabled number on the Wavix platform. */
    to?: string;
    /** Filters messages by delivery status. Accepts a `MessageDeliveryStatus` value. */
    status?: Wavix.MessageDeliveryStatus;
    /** Filters messages by `tag`. Supported for outbound messages only. */
    tag?: string;
    /** Filters messages by type. One of `sms` (text message) or `mms` (multimedia message). */
    message_type?: Wavix.smsAndMms.ListMessagesRequestMessageType;
    /** Page number to retrieve. Default `1`. */
    page?: number;
    /** Number of records to return per page. Default `25`. */
    per_page?: number;
}
