// This file was auto-generated by Fern from our API Definition.

import * as Wavix from "../../../src/api/index";
import { WavixClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("TransactionsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            is_empty: false,
            transactions: [
                {
                    id: 24789389,
                    date: "2023-08-29T14:48:38Z",
                    amount: -0.99,
                    balance_after: 309.0601,
                    details: "Monthly fee for 16419252149",
                    status: "Committed",
                    type: 3,
                    show_invoice: false,
                },
            ],
            pagination: { current_page: 1, per_page: 25, total: 1, total_pages: 1 },
        };

        server
            .mockEndpoint()
            .get("/v1/billing/transactions")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.billing.transactions.list({
            from_date: "2023-08-01",
            to_date: "2023-08-31",
            details_contains: "monthly",
            payments: true,
            page: 1,
            per_page: 25,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/billing/transactions")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billing.transactions.list({
                from_date: "2023-01-15",
                to_date: "2023-01-15",
            });
        }).rejects.toThrow(Wavix.BadRequestError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/billing/transactions")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billing.transactions.list({
                from_date: "2023-01-15",
                to_date: "2023-01-15",
            });
        }).rejects.toThrow(Wavix.ForbiddenError);
    });

    test("list (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/v1/billing/transactions")
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billing.transactions.list({
                from_date: "2023-01-15",
                to_date: "2023-01-15",
            });
        }).rejects.toThrow(Wavix.ServiceUnavailableError);
    });
});
