// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         url: "https://you-site.com/webhook",
 *         event_type: "post-call"
 *     }
 */
export interface CallWebhooksCreateRequest {
    /** Webhook URL to send call events to. */
    url: string;
    /**
     * Allowed values: `on-call`, `post-call`.
     *  - `on-call`: Sends real-time status updates
     *   when a call starts, is answered, and ends.
     *
     *  - `post-call`: Sends a callback after the call ends
     *   with disposition, duration, and cost.
     */
    event_type: CallWebhooksCreateRequest.EventType;
}

export namespace CallWebhooksCreateRequest {
    /**
     * Allowed values: `on-call`, `post-call`.
     *  - `on-call`: Sends real-time status updates
     *   when a call starts, is answered, and ends.
     *
     *  - `post-call`: Sends a callback after the call ends
     *   with disposition, duration, and cost.
     */
    export const EventType = {
        PostCall: "post-call",
        OnCall: "on-call",
    } as const;
    export type EventType = (typeof EventType)[keyof typeof EventType];
}
