// This file was auto-generated by Fern from our API Definition.

import * as Wavix from "../../src/api/index";
import { WavixClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("CartClient", () => {
    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            dids: [
                {
                    id: 541139862174,
                    activation_fee: "15.0",
                    monthly_fee: "10.0",
                    per_min: "0.01",
                    channels: "4",
                    city: "Buenos Aires",
                    country: "Argentina",
                    country_short_name: "AR",
                    cnam: false,
                    free_min: 0,
                    number: "541139862174",
                    require_docs: [1, 3],
                    sms_enabled: false,
                    sms_price: 0,
                    domestic_cli: false,
                },
            ],
            doc_types: [
                { id: 1, name: "id", title: "Any form of ID" },
                { id: 2, name: "address", title: "Proof of address" },
                { id: 3, name: "localaddress", title: "Proof of local address" },
            ],
        };

        server.mockEndpoint().get("/v1/buy/cart").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.cart.get();
        expect(response).toEqual(rawResponseBody);
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/v1/buy/cart").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.cart.get();
        }).rejects.toThrow(Wavix.BadRequestError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/v1/buy/cart").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.cart.get();
        }).rejects.toThrow(Wavix.ForbiddenError);
    });

    test("add (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { ids: ["541139862174", "541139862175"] };
        const rawResponseBody = [
            {
                activation_fee: "15.0",
                channels: "4",
                city: "Buenos Aires",
                cnam: false,
                country: "Argentina",
                country_short_name: "AR",
                domestic_cli: false,
                free_min: 0,
                id: 541139862174,
                monthly_fee: "10.0",
                number: "541139862174",
                per_min: "0.01",
                sms_enabled: false,
                sms_price: 0,
            },
        ];

        server
            .mockEndpoint()
            .put("/v1/buy/cart")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.cart.add({
            ids: ["541139862174", "541139862175"],
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("add (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { ids: ["ids", "ids"] };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/v1/buy/cart")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.cart.add({
                ids: ["ids", "ids"],
            });
        }).rejects.toThrow(Wavix.BadRequestError);
    });

    test("add (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { ids: ["ids", "ids"] };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/v1/buy/cart")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.cart.add({
                ids: ["ids", "ids"],
            });
        }).rejects.toThrow(Wavix.ForbiddenError);
    });

    test("add (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { ids: ["ids", "ids"] };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/v1/buy/cart")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.cart.add({
                ids: ["ids", "ids"],
            });
        }).rejects.toThrow(Wavix.NotFoundError);
    });

    test("remove (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { ids: ["541139862174", "541139862175"] };
        const rawResponseBody = { success: true };

        server
            .mockEndpoint()
            .delete("/v1/buy/cart")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.cart.remove({
            ids: ["541139862174", "541139862175"],
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("remove (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { ids: ["ids", "ids"] };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/v1/buy/cart")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.cart.remove({
                ids: ["ids", "ids"],
            });
        }).rejects.toThrow(Wavix.BadRequestError);
    });

    test("remove (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { ids: ["ids", "ids"] };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/v1/buy/cart")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.cart.remove({
                ids: ["ids", "ids"],
            });
        }).rejects.toThrow(Wavix.ForbiddenError);
    });

    test("remove (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { ids: ["ids", "ids"] };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/v1/buy/cart")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.cart.remove({
                ids: ["ids", "ids"],
            });
        }).rejects.toThrow(Wavix.NotFoundError);
    });

    test("checkout (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { ids: ["541139862174", "541139862175"] };
        const rawResponseBody = { success: true };

        server
            .mockEndpoint()
            .post("/v1/buy/cart/checkout")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.cart.checkout({
            ids: ["541139862174", "541139862175"],
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("checkout (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { ids: ["ids", "ids"] };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/buy/cart/checkout")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.cart.checkout({
                ids: ["ids", "ids"],
            });
        }).rejects.toThrow(Wavix.ForbiddenError);
    });

    test("checkout (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { ids: ["ids", "ids"] };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/buy/cart/checkout")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.cart.checkout({
                ids: ["ids", "ids"],
            });
        }).rejects.toThrow(Wavix.NotFoundError);
    });
});
