// This file was auto-generated by Fern from our API Definition.

import * as Wavix from "../../src/api/index";
import { WavixClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("CdrsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            items: [
                {
                    date: "2023-08-21T06:43:36Z",
                    from: "14302287001",
                    to: "33170363950",
                    disposition: "answered",
                    duration: 6,
                    destination: "France",
                    per_minute: "0.027",
                    charge: "0.822",
                    sip_trunk: "32882",
                    forward_fee: "0.0",
                    uuid: "99df5ffd-962a-410f-bcce-d08f1f7f328c",
                    call_id: "99df5ffd-962a-410f-bcce-d08f1f7f328c",
                    parent_call_id: "99df5ffd-962a-410f-bcce-d08f1f7f328c",
                    answered_by: "human",
                },
            ],
            pagination: { current_page: 2, per_page: 25, total: 101, total_pages: 5 },
        };

        server.mockEndpoint().get("/v1/cdrs").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.cdrs.list({
            from: "2023-01-01",
            to: "2023-09-01",
            type: "received",
            from_search: "13524815863",
            to_search: "12565378257",
            sip_trunk: "12321",
            uuid: "99df5ffd-962a-410f-bcce-d08f1f7f328c",
            page: 1,
            per_page: 25,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/v1/cdrs").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.cdrs.list({
                from: "2023-01-15",
                to: "2023-01-15",
                type: "type",
            });
        }).rejects.toThrow(Wavix.BadRequestError);
    });

    test("search (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { type: "placed", from: "2023-08-01", to: "2023-08-31", page: 1, per_page: 50 };
        const rawResponseBody = {
            items: [
                {
                    answered_by: "human",
                    date: "2023-08-21T06:43:36Z",
                    from: "14302287001",
                    to: "33170363950",
                    disposition: "answered",
                    duration: 6,
                    destination: "France",
                    per_minute: "0.027",
                    charge: "example",
                    sip_trunk: "32882",
                    forward_fee: "0.0",
                    uuid: "99df5ffd-962a-410f-bcce-d08f1f7f328c",
                    call_id: "99df5ffd-962a-410f-bcce-d08f1f7f328c",
                    parent_call_id: "99df5ffd-962a-410f-bcce-d08f1f7f328c",
                    transcription: {
                        uuid: "40d6f322-048d-490b-95c7-4fc5c76a74db",
                        url: "https://api.wavix.com/v1/cdrs/40d6f322-048d-490b-95c7-4fc5c76a74db/transcription?appid=secret",
                    },
                },
            ],
            pagination: { current_page: 2, per_page: 25, total: 101, total_pages: 5 },
        };

        server
            .mockEndpoint()
            .post("/v1/cdrs")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.cdrs.search({
            type: "placed",
            from: "2023-08-01",
            to: "2023-08-31",
            page: 1,
            per_page: 50,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("search (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { type: "placed", from: "2023-01-15", to: "2023-01-15", page: 1, per_page: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/cdrs")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.cdrs.search({
                type: "placed",
                from: "2023-01-15",
                to: "2023-01-15",
                page: 1,
                per_page: 1,
            });
        }).rejects.toThrow(Wavix.ForbiddenError);
    });

    test("search (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { type: "placed", from: "2023-01-15", to: "2023-01-15", page: 1, per_page: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/cdrs")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.cdrs.search({
                type: "placed",
                from: "2023-01-15",
                to: "2023-01-15",
                page: 1,
                per_page: 1,
            });
        }).rejects.toThrow(Wavix.UnprocessableEntityError);
    });

    test("retranscribe (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { success: true };

        server
            .mockEndpoint()
            .put("/v1/cdrs/bbaa37bf-430a-46da-ade3-c248e407016/retranscribe")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.cdrs.retranscribe({
            call_id: "bbaa37bf-430a-46da-ade3-c248e407016",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("retranscribe (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/v1/cdrs/call_id/retranscribe")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.cdrs.retranscribe({
                call_id: "call_id",
            });
        }).rejects.toThrow(Wavix.ForbiddenError);
    });

    test("retranscribe (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/v1/cdrs/call_id/retranscribe")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.cdrs.retranscribe({
                call_id: "call_id",
            });
        }).rejects.toThrow(Wavix.NotFoundError);
    });

    test("retranscribe (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/v1/cdrs/call_id/retranscribe")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.cdrs.retranscribe({
                call_id: "call_id",
            });
        }).rejects.toThrow(Wavix.UnprocessableEntityError);
    });

    test("transcriptions (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            transcript: { "16572026750": "", "16465292513": "" },
            turns: [
                { type: "46844685344", s: 160, e: 7280, text: "Hello, how can I help you?", sentiment: "neutral" },
                {
                    type: "+16572026750",
                    s: 2400,
                    e: 3280,
                    text: "Hello, I have a question about my bill.",
                    sentiment: "neutral",
                },
            ],
            uuid: "e84f350f-6da7-4b56-80eb-41dec572626b",
            language: "en",
            duration: 102,
            charge: "0.01",
            status: "completed",
            transcription_date: "2023-01-09T10:04:39Z",
            call_date: "2023-01-09T10:01:13Z",
            call_uuid: "bbaa37bf-430a-46da-ade3-c248e4070161",
            call_score: "3.8",
            call_summary: "The agent and client discussed billing issues.",
        };

        server
            .mockEndpoint()
            .get("/v1/cdrs/bbaa37bf-430a-46da-ade3-c248e407016/transcriptions")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.cdrs.transcriptions({
            call_id: "bbaa37bf-430a-46da-ade3-c248e407016",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("transcriptions (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/cdrs/call_id/transcriptions")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.cdrs.transcriptions({
                call_id: "call_id",
            });
        }).rejects.toThrow(Wavix.ForbiddenError);
    });

    test("transcriptions (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/cdrs/call_id/transcriptions")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.cdrs.transcriptions({
                call_id: "call_id",
            });
        }).rejects.toThrow(Wavix.NotFoundError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            date: "2023-08-21T06:43:36Z",
            from: "14302287001",
            to: "33170363950",
            disposition: "answered",
            duration: 6,
            destination: "France",
            per_minute: "0.027",
            recording_url: "https://api.wavix.com/v1/recordings/recording_id",
            charge: "0.162",
            sip_trunk: "32882",
            forward_fee: "0.0",
            uuid: "99df5ffd-962a-410f-bcce-d08f1f7f328c",
            call_id: "99df5ffd-962a-410f-bcce-d08f1f7f328c",
            parent_call_id: "99df5ffd-962a-410f-bcce-d08f1f7f328c",
            answered_by: "human",
            transcription: {
                uuid: "40d6f322-048d-490b-95c7-4fc5c76a74db",
                url: "https://api.wavix.com/v1/cdrs/40d6f322-048d-490b-95c7-4fc5c76a74db/transcription?appid=secret",
            },
        };

        server
            .mockEndpoint()
            .get("/v1/cdrs/aa566501-c591-4a8b-b3b9-cc1295398b72")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.cdrs.get({
            call_id: "aa566501-c591-4a8b-b3b9-cc1295398b72",
            show_transcription: true,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/v1/cdrs/call_id").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.cdrs.get({
                call_id: "call_id",
            });
        }).rejects.toThrow(Wavix.NotFoundError);
    });

    test("listAll (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody =
            '{"charge":"0.0059","date":"2023-08-28T15:43:31.000Z","destination":"My trunk","disposition":"answered","duration":26,"forward_fee":"0.0","from":"13524815863","per_minute":"0.0059","to":"12565378257","uuid":"99df5ffd-962a-410f-bcce-d08f1f7f328c"}\n{"charge":"0.00325","date":"2023-11-29T14:48:50.000Z","destination":"United States","disposition":"answered","duration":21,"from":"17182444444","per_minute":"0.0065","to":"18007009909","uuid":"aa566501-c591-4a8b-b3b9-cc1295398b72","forward_fee":"0.003"}';

        server.mockEndpoint().get("/v1/cdrs/all").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.cdrs.listAll({
            from: "2023-01-01",
            to: "2023-09-01",
            type: "received",
            from_search: "13524815863",
            to_search: "12565378257",
            sip_trunk: "12321",
            uuid: "99df5ffd-962a-410f-bcce-d08f1f7f328c",
            page: 1,
            per_page: 25,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("listAll (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/v1/cdrs/all").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.cdrs.listAll({
                from: "2023-01-15",
                to: "2023-01-15",
                type: "type",
            });
        }).rejects.toThrow(Wavix.ForbiddenError);
    });
});
