// This file was auto-generated by Fern from our API Definition.

import * as Wavix from "../../src/api/index";
import { WavixClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("LinkShortenerClient", () => {
    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { link: "https://your-site.com/long-url" };
        const rawResponseBody = { short_link: "https://wx.com/hd82Jhs21" };

        server
            .mockEndpoint()
            .post("/v1/short-links")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.linkShortener.create({
            link: "https://your-site.com/long-url",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { link: "link" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/short-links")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.linkShortener.create({
                link: "link",
            });
        }).rejects.toThrow(Wavix.BadRequestError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { link: "link" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/short-links")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.linkShortener.create({
                link: "link",
            });
        }).rejects.toThrow(Wavix.ForbiddenError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { link: "link" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/short-links")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.linkShortener.create({
                link: "link",
            });
        }).rejects.toThrow(Wavix.NotFoundError);
    });

    test("create (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { link: "link" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/short-links")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.linkShortener.create({
                link: "link",
            });
        }).rejects.toThrow(Wavix.UnprocessableEntityError);
    });
});
