// This file was auto-generated by Fern from our API Definition.

import * as Wavix from "../../src/api/index";
import { WavixClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("NumberValidatorClient", () => {
    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            phone_number: "971569483322",
            valid: true,
            country_code: "AE",
            e164_format: "+971569483322",
            national_format: "056 948 3322",
            ported: false,
            mcc: "424",
            mnc: "02",
            number_type: "mobile",
            carrier_name: "Etisalat",
            risky_destination: false,
            unallocated_range: false,
            reachable: true,
            roaming: false,
            timezone: "UTC+04:00",
            charge: "0.015",
            error_code: "000",
        };

        server.mockEndpoint().get("/v1/validation").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.numberValidator.get({
            phone_number: "971569483322",
            type: "format",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/v1/validation").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.numberValidator.get({
                phone_number: "phone_number",
                type: "format",
            });
        }).rejects.toThrow(Wavix.BadRequestError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/v1/validation").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.numberValidator.get({
                phone_number: "phone_number",
                type: "format",
            });
        }).rejects.toThrow(Wavix.ForbiddenError);
    });

    test("createBulk (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            phone_numbers: ["971501390098", "971504359195"],
            type: "format",
            async: true,
            force: true,
        };
        const rawResponseBody = {
            status: "success",
            pending: 0,
            count: 1000,
            items: [
                {
                    phone_number: "971569483322",
                    valid: true,
                    country_code: "AE",
                    e164_format: "+971569483322",
                    national_format: "056 948 3322",
                    ported: false,
                    mcc: "424",
                    mnc: "004",
                    number_type: "mobile",
                    carrier_name: "Etisalat",
                    risky_destination: false,
                    unallocated_range: false,
                    reachable: true,
                    roaming: false,
                    timezone: "UTC+04:00",
                    charge: "0.015",
                    error_code: "000",
                },
            ],
        };

        server
            .mockEndpoint()
            .post("/v1/validation")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.numberValidator.createBulk({
            phone_numbers: ["971501390098", "971504359195"],
            type: "format",
            async: true,
            force: true,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createBulk (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            phone_numbers: ["phone_numbers", "phone_numbers"],
            type: "format",
            async: true,
            force: true,
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/validation")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.numberValidator.createBulk({
                phone_numbers: ["phone_numbers", "phone_numbers"],
                type: "format",
                async: true,
                force: true,
            });
        }).rejects.toThrow(Wavix.BadRequestError);
    });

    test("createBulk (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            phone_numbers: ["phone_numbers", "phone_numbers"],
            type: "format",
            async: true,
            force: true,
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/validation")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.numberValidator.createBulk({
                phone_numbers: ["phone_numbers", "phone_numbers"],
                type: "format",
                async: true,
                force: true,
            });
        }).rejects.toThrow(Wavix.ForbiddenError);
    });

    test("createBulk (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            phone_numbers: ["phone_numbers", "phone_numbers"],
            type: "format",
            async: true,
            force: true,
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/validation")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.numberValidator.createBulk({
                phone_numbers: ["phone_numbers", "phone_numbers"],
                type: "format",
                async: true,
                force: true,
            });
        }).rejects.toThrow(Wavix.NotFoundError);
    });
});
