// This file was auto-generated by Fern from our API Definition.

import * as Wavix from "../../src/api/index";
import { WavixClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("NumbersClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            items: [
                {
                    id: 123,
                    number: "12565378257",
                    activation_fee: "0.99",
                    monthly_fee: "0.99",
                    per_min: "0.01",
                    city: "DETROIT, MI",
                    state: "example",
                    country: "United States",
                    country_short_name: "US",
                    destination: [
                        {
                            id: 1,
                            destination: "[did]@sipuri.com",
                            priority: 1,
                            transport: 1,
                            trunk_id: 23123,
                            srtp: false,
                            trunk_label: "My trunk",
                        },
                    ],
                    channels: 24,
                    require_docs: ["1"],
                    documents: [
                        {
                            id: 423,
                            allow_replace: false,
                            did_number: "12565378257",
                            doc_content_type: "image/png",
                            doc_file_name: "Copy of ID.png",
                            doc_type_id: 1,
                            status: "approved",
                            url: "https://api.wavix.com/v1/numbers/24882/papers/1",
                        },
                    ],
                    domestic_cli: true,
                    free_min: 123,
                    unlimited: true,
                    label: "example",
                    status: "example",
                    seconds: "example",
                    added: "2023-04-10T06:42:59Z",
                    paid_until: "2023-12-07",
                    sms_enabled: false,
                    sms_relay_url: "https://your-website.com/webhook",
                    cnam: true,
                    call_recording_enabled: true,
                    transcription_enabled: true,
                    transcription_threshold: 6,
                    call_status_url: "https://example.com",
                },
            ],
            doc_types: [{ id: 2, name: "address", title: "Proof of address" }],
            pagination: { current_page: 2, per_page: 25, total: 101, total_pages: 5 },
        };

        server.mockEndpoint().get("/v1/numbers").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.numbers.list({
            city_id: 123,
            search: "256537",
            label: "ALEX",
            label_present: true,
            page: 2,
            per_page: 50,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/v1/numbers").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.numbers.list();
        }).rejects.toThrow(Wavix.ForbiddenError);
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { success: true };

        server.mockEndpoint().delete("/v1/numbers").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.numbers.delete({
            dids: "47832123321,47832123324,478321233215",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().delete("/v1/numbers").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.numbers.delete();
        }).rejects.toThrow(Wavix.ForbiddenError);
    });

    test("delete (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().delete("/v1/numbers").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.numbers.delete();
        }).rejects.toThrow(Wavix.NotFoundError);
    });

    test("delete (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().delete("/v1/numbers").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.numbers.delete();
        }).rejects.toThrow(Wavix.UnprocessableEntityError);
    });

    test("bulkUpdate (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { ids: [123, 456] };
        const rawResponseBody = {
            items: [
                {
                    id: 123,
                    number: "12565378257",
                    activation_fee: "0.99",
                    monthly_fee: "0.99",
                    per_min: "0.01",
                    city: "DETROIT, MI",
                    state: "state",
                    country: "United States",
                    country_short_name: "US",
                    destination: [
                        {
                            id: 1,
                            destination: "[did]@sipuri.com",
                            priority: 1,
                            transport: 1,
                            trunk_id: 23123,
                            srtp: false,
                            trunk_label: "My trunk",
                        },
                    ],
                    channels: 24,
                    require_docs: ["1"],
                    documents: [
                        {
                            id: 423,
                            allow_replace: false,
                            did_number: "12565378257",
                            doc_content_type: "image/png",
                            doc_file_name: "Copy of ID.png",
                            doc_type_id: 1,
                            status: "approved",
                            url: "https://api.wavix.com/v1/numbers/24882/papers/1",
                        },
                    ],
                    domestic_cli: true,
                    free_min: 1,
                    unlimited: true,
                    label: "label",
                    status: "status",
                    seconds: "seconds",
                    added: "2023-04-10T06:42:59Z",
                    paid_until: "2023-12-07",
                    sms_enabled: false,
                    sms_relay_url: "https://your-website.com/webhook",
                    cnam: true,
                    call_recording_enabled: true,
                    transcription_enabled: true,
                    transcription_threshold: 6,
                    call_status_url: "https://example.com",
                },
            ],
        };

        server
            .mockEndpoint()
            .patch("/v1/numbers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.numbers.bulkUpdate({
            ids: [123, 456],
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("bulkUpdate (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { ids: [1, 1] };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/v1/numbers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.numbers.bulkUpdate({
                ids: [1, 1],
            });
        }).rejects.toThrow(Wavix.BadRequestError);
    });

    test("bulkUpdate (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { ids: [1, 1] };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/v1/numbers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.numbers.bulkUpdate({
                ids: [1, 1],
            });
        }).rejects.toThrow(Wavix.ForbiddenError);
    });

    test("bulkUpdate (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { ids: [1, 1] };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/v1/numbers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.numbers.bulkUpdate({
                ids: [1, 1],
            });
        }).rejects.toThrow(Wavix.NotFoundError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: 123,
            number: "12565378257",
            activation_fee: "0.99",
            monthly_fee: "0.99",
            per_min: "0.01",
            city: "DETROIT, MI",
            state: "example",
            country: "United States",
            country_short_name: "US",
            destination: [
                {
                    id: 1,
                    destination: "[did]@sipuri.com",
                    priority: 1,
                    transport: 1,
                    trunk_id: 23123,
                    srtp: false,
                    trunk_label: "My trunk",
                },
            ],
            channels: 24,
            require_docs: ["1"],
            documents: [
                {
                    id: 423,
                    allow_replace: false,
                    did_number: "12565378257",
                    doc_content_type: "image/png",
                    doc_file_name: "Copy of ID.png",
                    doc_type_id: 1,
                    status: "approved",
                    url: "https://api.wavix.com/v1/numbers/24882/papers/1",
                },
            ],
            domestic_cli: true,
            free_min: 123,
            unlimited: true,
            label: "example",
            status: "example",
            seconds: "example",
            added: "2023-04-10T06:42:59Z",
            paid_until: "2023-12-07",
            sms_enabled: false,
            sms_relay_url: "https://your-website.com/webhook",
            cnam: true,
            call_recording_enabled: true,
            transcription_enabled: true,
            transcription_threshold: 6,
            call_status_url: "https://example.com",
        };

        server.mockEndpoint().get("/v1/numbers/123").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.numbers.get({
            id: 123,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/v1/numbers/1").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.numbers.get({
                id: 1,
            });
        }).rejects.toThrow(Wavix.ForbiddenError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/v1/numbers/1").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.numbers.get({
                id: 1,
            });
        }).rejects.toThrow(Wavix.NotFoundError);
    });

    test("update (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            id: 123,
            number: "12565378257",
            activation_fee: "0.99",
            monthly_fee: "0.99",
            per_min: "0.01",
            city: "DETROIT, MI",
            state: "state",
            country: "United States",
            country_short_name: "US",
            destination: [
                {
                    id: 1,
                    destination: "[did]@sipuri.com",
                    priority: 1,
                    transport: 1,
                    trunk_id: 23123,
                    srtp: false,
                    trunk_label: "My trunk",
                },
            ],
            channels: 24,
            require_docs: ["1"],
            documents: [
                {
                    id: 423,
                    allow_replace: false,
                    did_number: "12565378257",
                    doc_content_type: "image/png",
                    doc_file_name: "Copy of ID.png",
                    doc_type_id: 1,
                    status: "approved",
                    url: "https://api.wavix.com/v1/numbers/24882/papers/1",
                },
            ],
            domestic_cli: true,
            free_min: 1,
            unlimited: true,
            label: "label",
            status: "status",
            seconds: "seconds",
            added: "2023-04-10T06:42:59Z",
            paid_until: "2023-12-07",
            sms_enabled: false,
            sms_relay_url: "https://your-website.com/webhook",
            cnam: true,
            call_recording_enabled: true,
            transcription_enabled: true,
            transcription_threshold: 6,
            call_status_url: "https://example.com",
        };

        server
            .mockEndpoint()
            .patch("/v1/numbers/123")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.numbers.update({
            id: 123,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("update (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/v1/numbers/1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.numbers.update({
                id: 1,
            });
        }).rejects.toThrow(Wavix.BadRequestError);
    });

    test("update (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/v1/numbers/1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.numbers.update({
                id: 1,
            });
        }).rejects.toThrow(Wavix.ForbiddenError);
    });

    test("update (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/v1/numbers/1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.numbers.update({
                id: 1,
            });
        }).rejects.toThrow(Wavix.NotFoundError);
    });
});
