// This file was auto-generated by Fern from our API Definition.

import * as Wavix from "../../../src/api/index";
import { WavixClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("AudioClient", () => {
    test("play (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { audio_file: "https://examples.com/audio.wav" };
        const rawResponseBody = { success: true };

        server
            .mockEndpoint()
            .post("/v1/calls/id/play")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.callControl.audio.play({
            id: "id",
            audio_file: "https://examples.com/audio.wav",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("play (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { audio_file: "audio_file" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/calls/id/play")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.callControl.audio.play({
                id: "id",
                audio_file: "audio_file",
            });
        }).rejects.toThrow(Wavix.BadRequestError);
    });

    test("play (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { audio_file: "audio_file" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/v1/calls/id/play")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.callControl.audio.play({
                id: "id",
                audio_file: "audio_file",
            });
        }).rejects.toThrow(Wavix.UnauthorizedError);
    });

    test("play (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { audio_file: "audio_file" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/calls/id/play")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.callControl.audio.play({
                id: "id",
                audio_file: "audio_file",
            });
        }).rejects.toThrow(Wavix.NotFoundError);
    });

    test("stop (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { success: true };

        server
            .mockEndpoint()
            .delete("/v1/calls/id/audio")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.callControl.audio.stop({
            id: "id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("stop (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/v1/calls/id/audio")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.callControl.audio.stop({
                id: "id",
            });
        }).rejects.toThrow(Wavix.UnauthorizedError);
    });

    test("stop (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/v1/calls/id/audio")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.callControl.audio.stop({
                id: "id",
            });
        }).rejects.toThrow(Wavix.NotFoundError);
    });
});
