// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         brand_id: "B9FXYNH",
 *         campaign_id: "CSJ4TV0",
 *         number: "17029641104"
 *     }
 */
export interface LinkCampaignNumbersRequest {
    /** The unique ID of the 10DLC Brand. */
    brand_id: string;
    /** The unique ID of the 10DLC Campaign. */
    campaign_id: string;
    /** The phone number to link to the Campaign, in E.164 format. */
    number: string;
}
