// This file was auto-generated by Fern from our API Definition.

import type * as Wavix from "../../../../index.js";

/**
 * @example
 *     {
 *         phone_number: "971569483322",
 *         type: "format"
 *     }
 */
export interface GetNumberValidatorRequest {
    /** The phone number to validate, in E.164 format with or without the leading `+`. */
    phone_number: string;
    /** Depth of validation to perform. Accepts a `PhoneNumberValidationType` value. */
    type: Wavix.PhoneNumberValidationType;
}
