// This file was auto-generated by Fern from our API Definition.

import type * as Wavix from "../../../../index.js";

/**
 * @example
 *     {
 *         phone_numbers: ["971501390098", "971504359195"],
 *         type: "format",
 *         async: true,
 *         force: true
 *     }
 */
export interface PhoneValidationRequest {
    /** List of phone numbers to get detailed information about. */
    phone_numbers: string[];
    type: Wavix.PhoneNumberValidationType;
    /** Indicates whether the request should be executed asynchronously. If `true`, the response will include a `request_uuid` that can be used to poll for results. If `false`, the response will include validation results directly. */
    async: boolean;
    /** Indicates whether to force a fresh validation instead of returning a previously cached result. */
    force: boolean;
}
