// This file was auto-generated by Fern from our API Definition.

import type * as Wavix from "../../../../index.js";

/**
 * @example
 *     {
 *         phone_numbers: ["971501390098", "971504359195"],
 *         type: "format"
 *     }
 */
export interface PhoneValidationRequest {
    /** List of phone numbers to get detailed information about. Maximum 1000 numbers per request. */
    phone_numbers: string[];
    type: Wavix.PhoneNumberValidationType;
    /** Indicates whether the request should be executed asynchronously. If `true`, the response will include a `request_uuid` that can be used to poll for results. If `false` (default), the response will include validation results directly. */
    async?: boolean;
    /** Indicates whether to force a fresh validation instead of returning a previously cached result. Defaults to `false`. */
    force?: boolean;
}
