// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         brand_id: "B6AI7PA",
 *         evp_id: "AEGIS",
 *         vetting_class: "STANDARD"
 *     }
 */
export interface TenDlcBrandVettingCreateRequest {
    /** The unique ID of the 10DLC Brand. */
    brand_id: string;
    /** Code identifying the external vetting provider to perform the vetting. */
    evp_id: string;
    /** Class of vetting to request, such as `STANDARD` or `ENHANCED`. */
    vetting_class: string;
}
