// This file was auto-generated by Fern from our API Definition.

import * as Wavix from "../../../src/api/index";
import { WavixClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("TransactionsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            transactions: [
                {
                    amount: 10.5,
                    balance_after: 100,
                    date: "2023-06-15T10:30:00Z",
                    details: "Account top-up",
                    status: "committed",
                    type: 1,
                },
            ],
            pagination: { current_page: 1, per_page: 25, total: 1, total_pages: 123 },
        };

        server
            .mockEndpoint()
            .get("/v1/sub-organizations/123/billing/transactions")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.subAccounts.transactions.list({
            id: 123,
            from_date: "2023-01-01",
            to_date: "2023-12-31",
            type: 1,
            page: 1,
            per_page: 25,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/v1/sub-organizations/1/billing/transactions")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.subAccounts.transactions.list({
                id: 1,
                from_date: "2023-01-15",
                to_date: "2023-01-15",
            });
        }).rejects.toThrow(Wavix.UnauthorizedError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/sub-organizations/1/billing/transactions")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.subAccounts.transactions.list({
                id: 1,
                from_date: "2023-01-15",
                to_date: "2023-01-15",
            });
        }).rejects.toThrow(Wavix.ForbiddenError);
    });

    test("list (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/sub-organizations/1/billing/transactions")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.subAccounts.transactions.list({
                id: 1,
                from_date: "2023-01-15",
                to_date: "2023-01-15",
            });
        }).rejects.toThrow(Wavix.NotFoundError);
    });

    test("list (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/v1/sub-organizations/1/billing/transactions")
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.subAccounts.transactions.list({
                id: 1,
                from_date: "2023-01-15",
                to_date: "2023-01-15",
            });
        }).rejects.toThrow(Wavix.ServiceUnavailableError);
    });
});
