// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         dba_name: "Brand",
 *         company_name: "Company",
 *         entity_type: "PRIVATE_PROFIT",
 *         status: "VERIFIED",
 *         country: "US",
 *         show_deleted: false,
 *         ein_taxid: "999999999",
 *         mock: false,
 *         created_before: "2024-08-22",
 *         created_after: "2024-08-22",
 *         page: 1,
 *         per_page: 25
 *     }
 */
export interface ListBrandsRequest {
    /** Filters Brands by `dba_name` (doing-business-as name). Matches partial values. */
    dba_name?: string;
    /** Filters Brands by `company_name` (registered legal name). Matches partial values. */
    company_name?: string;
    /** Filters Brands by business entity type, such as `PRIVATE_PROFIT`. */
    entity_type?: string;
    /** Filters Brands by identity verification status, such as `VERIFIED`. */
    status?: string;
    /** Filters Brands by registration country, as an ISO 3166-1 alpha-2 code (e.g., `US`). */
    country?: string;
    /** When `true`, includes deleted Brands in the results. Default `false`. */
    show_deleted?: boolean;
    /** Filters Brands by their Employer Identification Number (EIN) or tax ID. */
    ein_taxid?: string;
    /** When `true`, returns only mock Brands used for testing. Default `false`. */
    mock?: boolean;
    /** Returns brands created on or before this date, in `YYYY-MM-DD` format. */
    created_before?: string;
    /** Returns brands created on or after this date, in `YYYY-MM-DD` format. */
    created_after?: string;
    /** Page number to retrieve. Default `1`. */
    page?: number;
    /** Number of records to return per page. Default `25`. */
    per_page?: number;
}
