// This file was auto-generated by Fern from our API Definition.

import * as Wavix from "../../../src/api/index";
import { WavixClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("BrandEvidenceClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            items: [
                {
                    file_name: "file.png",
                    mime_type: "image/png",
                    url: "https://api.qa1.wavix.dev/v3/10dlc/brands/BRGQVL0/evidence/3d8d97b6-61f7-4f91-8c1c-7ef83828e072",
                    uuid: "3d8d97b6-61f7-4f91-8c1c-7ef83828e072",
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/v3/10dlc/brands/B6AI7PA/evidence")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tenDlc.brandEvidence.list({
            brand_id: "B6AI7PA",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v3/10dlc/brands/brand_id/evidence")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tenDlc.brandEvidence.list({
                brand_id: "brand_id",
            });
        }).rejects.toThrow(Wavix.ForbiddenError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v3/10dlc/brands/brand_id/evidence")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tenDlc.brandEvidence.list({
                brand_id: "brand_id",
            });
        }).rejects.toThrow(Wavix.NotFoundError);
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { success: true };

        server
            .mockEndpoint()
            .delete("/v3/10dlc/brands/B6AI7PA/evidence/191eb205-8357-4d71-b8da-160a25a000d7")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tenDlc.brandEvidence.delete({
            brand_id: "B6AI7PA",
            id: "191eb205-8357-4d71-b8da-160a25a000d7",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/v3/10dlc/brands/brand_id/evidence/id")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tenDlc.brandEvidence.delete({
                brand_id: "brand_id",
                id: "id",
            });
        }).rejects.toThrow(Wavix.ForbiddenError);
    });

    test("delete (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/v3/10dlc/brands/brand_id/evidence/id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tenDlc.brandEvidence.delete({
                brand_id: "brand_id",
                id: "id",
            });
        }).rejects.toThrow(Wavix.NotFoundError);
    });
});
