// This file was auto-generated by Fern from our API Definition.

import * as Wavix from "../../../src/api/index";
import { WavixClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("BrandVettingAppealsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = [
            {
                appeal_outcome: {
                    vet_status: "ACTIVE",
                    vet_score: 80,
                    feedback: {
                        reasons: [
                            "Company size as reported by government or business sources resulted in a score deduction: size range 6-10.",
                        ],
                    },
                },
                appeal_status: "COMPLETE",
                appeal_status_update_date: "2024-08-15T08:42:31Z",
                attachment_uuid_list: ["attachment_uuid_list"],
                brand_id: "BMQFB7X",
                category_list: ["LOW_SCORE"],
                create_date: "2024-08-15T08:41:05",
                explanation: "This is an API test",
                evp_id: "AEGIS",
                vetting_class: "STANDARD",
                vetting_id: "48c0ffaa-4e51-4d44-3982-08dcb9856232",
            },
        ];

        server
            .mockEndpoint()
            .get("/v3/10dlc/brands/BMQFB7X/vettings/appeals")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tenDlc.brandVettingAppeals.list({
            brand_id: "BMQFB7X",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v3/10dlc/brands/brand_id/vettings/appeals")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tenDlc.brandVettingAppeals.list({
                brand_id: "brand_id",
            });
        }).rejects.toThrow(Wavix.ForbiddenError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v3/10dlc/brands/brand_id/vettings/appeals")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tenDlc.brandVettingAppeals.list({
                brand_id: "brand_id",
            });
        }).rejects.toThrow(Wavix.NotFoundError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            appeal_categories: ["VERIFY_TAX_ID"],
            evidence: ["855dff49-c097-4645-3983-08dcb9856232"],
        };
        const rawResponseBody = { success: true };

        server
            .mockEndpoint()
            .post("/v3/10dlc/brands/B6AI7PA/vettings/appeals")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tenDlc.brandVettingAppeals.create({
            brand_id: "B6AI7PA",
            appeal_categories: ["VERIFY_TAX_ID"],
            evidence: ["855dff49-c097-4645-3983-08dcb9856232"],
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            appeal_categories: ["appeal_categories", "appeal_categories"],
            evidence: ["evidence", "evidence"],
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v3/10dlc/brands/brand_id/vettings/appeals")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tenDlc.brandVettingAppeals.create({
                brand_id: "brand_id",
                appeal_categories: ["appeal_categories", "appeal_categories"],
                evidence: ["evidence", "evidence"],
            });
        }).rejects.toThrow(Wavix.ForbiddenError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            appeal_categories: ["appeal_categories", "appeal_categories"],
            evidence: ["evidence", "evidence"],
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v3/10dlc/brands/brand_id/vettings/appeals")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tenDlc.brandVettingAppeals.create({
                brand_id: "brand_id",
                appeal_categories: ["appeal_categories", "appeal_categories"],
                evidence: ["evidence", "evidence"],
            });
        }).rejects.toThrow(Wavix.NotFoundError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            appeal_categories: ["appeal_categories", "appeal_categories"],
            evidence: ["evidence", "evidence"],
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v3/10dlc/brands/brand_id/vettings/appeals")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tenDlc.brandVettingAppeals.create({
                brand_id: "brand_id",
                appeal_categories: ["appeal_categories", "appeal_categories"],
                evidence: ["evidence", "evidence"],
            });
        }).rejects.toThrow(Wavix.UnprocessableEntityError);
    });
});
