// This file was auto-generated by Fern from our API Definition.

import * as Wavix from "../../../src/api/index";
import { WavixClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("BrandsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            items: [
                {
                    brand_id: "BM20QP9",
                    dba_name: "New Brand",
                    company_name: "Company legal name",
                    entity_type: "PRIVATE_PROFIT",
                    vertical: "HEALTHCARE",
                    ein_taxid: "999999999",
                    ein_taxid_country: "US",
                    status: "VERIFIED",
                    website: "https://brand.com",
                    first_name: "John",
                    last_name: "Dow",
                    phone_number: "12123450099",
                    email: "support@brand.com",
                    street_address: "10, Street Name",
                    city: "Miami",
                    state_or_province: "FL",
                    country: "US",
                    zip: "12345",
                    feedback: null,
                    mock: false,
                    created_at: "2024-07-24T08:10:49",
                    updated_at: "2024-07-24T08:29:09",
                },
            ],
            pagination: { current_page: 1, per_page: 25, total: 1, total_pages: 1 },
        };

        server.mockEndpoint().get("/v3/10dlc/brands").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.tenDlc.brands.list({
            dba_name: "Brand",
            company_name: "Company",
            entity_type: "PRIVATE_PROFIT",
            status: "VERIFIED",
            country: "US",
            show_deleted: false,
            ein_taxid: "999999999",
            mock: false,
            created_before: "2024-08-22",
            created_after: "2024-08-22",
            page: 1,
            per_page: 25,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/v3/10dlc/brands").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.tenDlc.brands.list();
        }).rejects.toThrow(Wavix.BadRequestError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/v3/10dlc/brands").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.tenDlc.brands.list();
        }).rejects.toThrow(Wavix.ForbiddenError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            brand_id: "BM20QP9",
            dba_name: "New Brand",
            company_name: "Company legal name",
            entity_type: "PRIVATE_PROFIT",
            vertical: "HEALTHCARE",
            ein_taxid: "99999999",
            ein_taxid_country: "US",
            status: "REVIEW",
            website: "https://brand.com",
            first_name: "John",
            last_name: "Dow",
            phone_number: "12123450099",
            email: "support@brand.com",
            street_address: "10, Street Name",
            city: "Miami",
            state_or_province: "FL",
            country: "US",
            zip: "12345",
            feedback: null,
            mock: false,
            created_at: "2024-07-24T08:10:49",
            updated_at: "2024-07-24T08:10:49",
        };

        server
            .mockEndpoint()
            .post("/v3/10dlc/brands")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tenDlc.brands.create({});
        expect(response).toEqual(rawResponseBody);
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v3/10dlc/brands")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tenDlc.brands.create({});
        }).rejects.toThrow(Wavix.BadRequestError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v3/10dlc/brands")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tenDlc.brands.create({});
        }).rejects.toThrow(Wavix.ForbiddenError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            brand_id: "BM20QP9",
            dba_name: "New Brand",
            company_name: "Company legal name",
            entity_type: "PRIVATE_PROFIT",
            vertical: "HEALTHCARE",
            ein_taxid: "99999999",
            ein_taxid_country: "US",
            status: "VERIFIED",
            website: "https://brand.com",
            first_name: "John",
            last_name: "Dow",
            phone_number: "12123450099",
            email: "support@brand.com",
            street_address: "10, Street Name",
            city: "Miami",
            state_or_province: "FL",
            country: "US",
            zip: "12345",
            feedback: null,
            mock: false,
            created_at: "2024-07-24T08:10:49",
            updated_at: "2024-07-24T08:29:09",
        };

        server
            .mockEndpoint()
            .get("/v3/10dlc/brands/BM20QP9")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tenDlc.brands.get({
            brand_id: "BM20QP9",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v3/10dlc/brands/brand_id")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tenDlc.brands.get({
                brand_id: "brand_id",
            });
        }).rejects.toThrow(Wavix.ForbiddenError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v3/10dlc/brands/brand_id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tenDlc.brands.get({
                brand_id: "brand_id",
            });
        }).rejects.toThrow(Wavix.NotFoundError);
    });

    test("update (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            brand_id: "BM20QP9",
            dba_name: "New Brand",
            company_name: "Company legal name",
            entity_type: "PRIVATE_PROFIT",
            vertical: "HEALTHCARE",
            ein_taxid: "99999999",
            ein_taxid_country: "US",
            status: "REVIEW",
            website: "https://brand.com",
            first_name: "John",
            last_name: "Dow",
            phone_number: "12123450099",
            email: "support@brand.com",
            street_address: "10, Street Name",
            city: "Miami",
            state_or_province: "FL",
            country: "US",
            zip: "12345",
            feedback: null,
            mock: false,
            created_at: "2024-07-24T08:10:49",
            updated_at: "2024-07-24T09:02:19",
        };

        server
            .mockEndpoint()
            .put("/v3/10dlc/brands/BM20QP9")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tenDlc.brands.update({
            brand_id: "BM20QP9",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("update (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/v3/10dlc/brands/brand_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tenDlc.brands.update({
                brand_id: "brand_id",
            });
        }).rejects.toThrow(Wavix.BadRequestError);
    });

    test("update (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/v3/10dlc/brands/brand_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tenDlc.brands.update({
                brand_id: "brand_id",
            });
        }).rejects.toThrow(Wavix.ForbiddenError);
    });

    test("update (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/v3/10dlc/brands/brand_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tenDlc.brands.update({
                brand_id: "brand_id",
            });
        }).rejects.toThrow(Wavix.NotFoundError);
    });

    test("update (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/v3/10dlc/brands/brand_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tenDlc.brands.update({
                brand_id: "brand_id",
            });
        }).rejects.toThrow(Wavix.UnprocessableEntityError);
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { success: true };

        server
            .mockEndpoint()
            .delete("/v3/10dlc/brands/BM20QP9")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tenDlc.brands.delete({
            brand_id: "BM20QP9",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/v3/10dlc/brands/brand_id")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tenDlc.brands.delete({
                brand_id: "brand_id",
            });
        }).rejects.toThrow(Wavix.ForbiddenError);
    });

    test("delete (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/v3/10dlc/brands/brand_id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tenDlc.brands.delete({
                brand_id: "brand_id",
            });
        }).rejects.toThrow(Wavix.NotFoundError);
    });

    test("qualifyUsecase (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            mno_metadata: [
                {
                    att_mms_tpm: null,
                    att_msg_class: null,
                    att_sms_tpm: null,
                    att_tpm_scope: null,
                    help_required: true,
                    optin_required: true,
                    optout_required: false,
                    min_msg_samples: 1,
                    mno: "T-Mobile",
                    mno_qualify: true,
                    mno_review: false,
                    mno_support: true,
                    no_embedded_links: false,
                    no_embedded_phone: false,
                    tmobile_brand_dcap: 2000,
                    tmobile_brand_tier: "LOW",
                },
            ],
            monthly_fee: 10,
            usecase: "2FA",
        };

        server
            .mockEndpoint()
            .get("/v3/10dlc/brands/BMQFB7X/usecases/AGENTS_FRANCHISES")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tenDlc.brands.qualifyUsecase({
            brand_id: "BMQFB7X",
            use_case: "AGENTS_FRANCHISES",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("qualifyUsecase (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v3/10dlc/brands/brand_id/usecases/AGENTS_FRANCHISES")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tenDlc.brands.qualifyUsecase({
                brand_id: "brand_id",
                use_case: "AGENTS_FRANCHISES",
            });
        }).rejects.toThrow(Wavix.ForbiddenError);
    });

    test("qualifyUsecase (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v3/10dlc/brands/brand_id/usecases/AGENTS_FRANCHISES")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tenDlc.brands.qualifyUsecase({
                brand_id: "brand_id",
                use_case: "AGENTS_FRANCHISES",
            });
        }).rejects.toThrow(Wavix.NotFoundError);
    });

    test("qualifyUsecase (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v3/10dlc/brands/brand_id/usecases/AGENTS_FRANCHISES")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tenDlc.brands.qualifyUsecase({
                brand_id: "brand_id",
                use_case: "AGENTS_FRANCHISES",
            });
        }).rejects.toThrow(Wavix.UnprocessableEntityError);
    });
});
