// This file was auto-generated by Fern from our API Definition.

import * as Wavix from "../../../src/api/index";
import { WavixClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("CampaignNumbersClient", () => {
    test("link (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { success: true };

        server
            .mockEndpoint()
            .post("/v3/10dlc/brands/B9FXYNH/campaigns/CSJ4TV0/numbers/17029641104")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tenDlc.campaignNumbers.link({
            brand_id: "B9FXYNH",
            campaign_id: "CSJ4TV0",
            number: "17029641104",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("link (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v3/10dlc/brands/brand_id/campaigns/campaign_id/numbers/number")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tenDlc.campaignNumbers.link({
                brand_id: "brand_id",
                campaign_id: "campaign_id",
                number: "number",
            });
        }).rejects.toThrow(Wavix.ForbiddenError);
    });

    test("link (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v3/10dlc/brands/brand_id/campaigns/campaign_id/numbers/number")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tenDlc.campaignNumbers.link({
                brand_id: "brand_id",
                campaign_id: "campaign_id",
                number: "number",
            });
        }).rejects.toThrow(Wavix.NotFoundError);
    });

    test("unlink (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { success: true };

        server
            .mockEndpoint()
            .delete("/v3/10dlc/brands/B9FXYNH/campaigns/CSJ4TV0/numbers/17029641104")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tenDlc.campaignNumbers.unlink({
            brand_id: "B9FXYNH",
            campaign_id: "CSJ4TV0",
            number: "17029641104",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("unlink (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/v3/10dlc/brands/brand_id/campaigns/campaign_id/numbers/number")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tenDlc.campaignNumbers.unlink({
                brand_id: "brand_id",
                campaign_id: "campaign_id",
                number: "number",
            });
        }).rejects.toThrow(Wavix.ForbiddenError);
    });

    test("unlink (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/v3/10dlc/brands/brand_id/campaigns/campaign_id/numbers/number")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tenDlc.campaignNumbers.unlink({
                brand_id: "brand_id",
                campaign_id: "campaign_id",
                number: "number",
            });
        }).rejects.toThrow(Wavix.NotFoundError);
    });

    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            brand_id: "B9FXYNH",
            campaign_id: "CSJ4TV0",
            numbers: [{ number: "17029641104", status: "APPROVED" }],
        };

        server
            .mockEndpoint()
            .get("/v3/10dlc/brands/B9FXYNH/campaigns/CSJ4TV0/numbers")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tenDlc.campaignNumbers.list({
            brand_id: "B9FXYNH",
            campaign_id: "CSJ4TV0",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v3/10dlc/brands/brand_id/campaigns/campaign_id/numbers")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tenDlc.campaignNumbers.list({
                brand_id: "brand_id",
                campaign_id: "campaign_id",
            });
        }).rejects.toThrow(Wavix.ForbiddenError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v3/10dlc/brands/brand_id/campaigns/campaign_id/numbers")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tenDlc.campaignNumbers.list({
                brand_id: "brand_id",
                campaign_id: "campaign_id",
            });
        }).rejects.toThrow(Wavix.NotFoundError);
    });
});
