// This file was auto-generated by Fern from our API Definition.

import * as Wavix from "../../../src/api/index";
import { WavixClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("SubscriptionsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = [{ subscription_category: "brand", url: "https://webhook.url" }];

        server
            .mockEndpoint()
            .get("/v3/10dlc/subscriptions")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tenDlc.subscriptions.list();
        expect(response).toEqual(rawResponseBody);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v3/10dlc/subscriptions")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tenDlc.subscriptions.list();
        }).rejects.toThrow(Wavix.ForbiddenError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { subscription_category: "brand", url: "https://webhook.url" };
        const rawResponseBody = { subscription_category: "brand", url: "https://webhook.url" };

        server
            .mockEndpoint()
            .post("/v3/10dlc/subscriptions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tenDlc.subscriptions.create({
            subscription_category: "brand",
            url: "https://webhook.url",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { subscription_category: "subscription_category", url: "url" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v3/10dlc/subscriptions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tenDlc.subscriptions.create({
                subscription_category: "subscription_category",
                url: "url",
            });
        }).rejects.toThrow(Wavix.ForbiddenError);
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { success: true };

        server
            .mockEndpoint()
            .delete("/v3/10dlc/subscriptions")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tenDlc.subscriptions.delete({
            subscription_category: "number",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/v3/10dlc/subscriptions")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tenDlc.subscriptions.delete({
                subscription_category: "subscription_category",
            });
        }).rejects.toThrow(Wavix.BadRequestError);
    });

    test("delete (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WavixClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/v3/10dlc/subscriptions")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tenDlc.subscriptions.delete({
                subscription_category: "subscription_category",
            });
        }).rejects.toThrow(Wavix.ForbiddenError);
    });
});
