// This file was auto-generated by Fern from our API Definition.

import type * as Wavix from "../../../../../index.js";

export interface ListRegionsResponse {
    /** States or provinces available for the requested country. */
    regions: Wavix.Region[];
}
