// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListCountriesRequest {
    /** When `true`, returns only countries that offer text-enabled phone numbers. */
    text_enabled_only?: boolean;
}
